Иерархия состояния
kruzhok-team/lapki-client pull request #153
Opened 2023-12-13 04:26 UTC by XidFanSan

ЧТО РЕАЛИЗОВАНО:
1) Реализована иерархия состояний со свежей версией проекта;
2) Есть отдельные кнопки "Раскрыть всё", "Свернуть всё" для удобства пользования;
3) Есть поиск;
4) Реализовано полная система взаимодействия иерархии с редактором, но взаимодействие редактора с иерархии ещё не полная;
ЧТО ПЛАНИРУЕТСЯ ДОРЕАЛИЗОВАТЬ:
1) Планируется реализовать фильтр для удобства и уменьшения используемого места на клиенте всеми кнопками и т.д.;
2) Добавление кнопок для показа только состояний или же связей;
3) Полное взаимодействие редактора с иерархией(Не хватает буквально пару функций);

2023-12-13 13:48 UTC, chekoopa commented
> Планируется реализовать фильтр для удобства и уменьшения используемого места на клиенте всеми кнопками и т.д.

В целом можно отдельным пулл-реквестом.

> Добавление кнопок для показа только состояний или же связей;

А в чём его пользовательский сценарий? Мне кажется, здесь полезнее режим, когда иерархия показывает только связи/состояния для выделенного элемента.

> Полное взаимодействие редактора с иерархией(Не хватает буквально пару функций)

Каких???

2023-12-13 14:09 UTC, XidFanSan commented
Тогда добавлю функционал показа отдельного состояния и его связей.
А пара функций, это:
1) множественный выбор, его можно реализовать, но в нашей логике работы с данными еще нет этого функционала, поэтому надо будет это все добавить отдельным пуллом;
2) и как раз взаимосвязанная функция с множественным выбором, это выбор в редакторе необходимого состояния и показывать его в иерархии, она как бы работает, но лишь когда изменяются основные данные для любого состояния(связи), тобишь координаты, название и т.д., а реагирования на выделения в EditorManager.tsx нет, что и вызывает данную недоработку.
P.s. в данном пулле я пока убрал выделения состояния(связи) в иерархии при выборе состояния(связи) в редакторе, пока не решу вопрос с недоработкой.

2023-12-18 10:09 UTC, bryzZz commented on src/renderer/src/hooks/useHierarchyManager.ts
> +    Object.entries(states)
```typescript
 for (const [stateId, state] of editor.container.machineController.states) {
      state.isSelected
      break;
    }
```

2023-12-18 10:09 UTC, bryzZz commented on src/renderer/src/hooks/useHierarchyManager.ts
> +        isFolder:
Проходить по вьюшкам

2023-12-18 10:09 UTC, bryzZz commented on demos/berlogaScheme(normal).json
> +{
УДАЛИ

2023-12-18 12:40 UTC, XidFanSan commented on src/renderer/src/App.tsx
> +  // const [update, setUpdate] = useState<CanvasEditor | null>(null);
Готово.

2023-12-18 12:50 UTC, XidFanSan commented on demos/berlogaScheme(normal).json
> +{
Готово.

2023-12-18 12:52 UTC, XidFanSan commented on src/renderer/src/components/Hierarchy/Hierarchy.tsx
> +                    onChange={onFunction}
Готово.

2023-12-18 14:37 UTC, XidFanSan commented on src/renderer/src/components/Hierarchy/Hierarchy.tsx
> +                    className="btn-primary mb-2 flex w-full items-center justify-center gap-3 placeholder-white"
Готово.

2023-12-19 07:21 UTC, XidFanSan commented on src/renderer/src/components/Hierarchy/Hierarchy.tsx
> +              Array.from(editor.container.machineController.states).map((state) => {
По ключу обратиться удалось, но другим способом, потому что find не работает

2023-12-19 10:37 UTC, XidFanSan commented on src/renderer/src/hooks/useHierarchyManager.ts
> +    Object.entries(states)
Готово.

2023-12-20 12:36 UTC, bryzZz requested changes
Стяни правки из upstream/main

2023-12-20 12:36 UTC, bryzZz commented on src/renderer/src/components/DiagramEditor.tsx
> -        <DiagramContextMenu {...contextMenu} />
DiagramContextMenu нужно оставить на холсте, а для иерархии сделать свой компонент. Элементы меню соответственно нужно вынести в отдельный массив и переиспользовать.
Ещё никто в жизни не найдёт что в иерархии есть контекстное меню, нужно сделать иконку с тремя точками в правой части элементов, чтобы на её нажатие открывалось меню

2023-12-20 12:36 UTC, bryzZz commented on src/renderer/src/components/Hierarchy/Hierarchy.tsx
> +  //Магия смены темы у данного компонента(На самом деле всё просто, он как ребёнок, получает все знания у своего родителя, которая связана со сменой темы)
Странный коммент, ты в коде пишешь "использовать тему (useThemeContext)" и оставляешь комментарий "тут мы используем тему". А я и не понял)

2023-12-20 12:36 UTC, bryzZz commented on src/renderer/src/components/Hierarchy/Hierarchy.tsx
> +export const Hierarchy: React.FC<{
Вынести интерфейс HierarchyProps

2023-12-20 12:36 UTC, bryzZz commented on src/renderer/src/hooks/useHierarchyManager.ts
> +  const id: string | undefined = useMemo(() => {
Нужно переназвать типа selectedItemId

2023-12-20 12:36 UTC, bryzZz commented on src/renderer/src/components/Hierarchy/Hierarchy.tsx
> +      return editor.container.statesController.handleContextMenu(state, { event: mouse });
Эти функции нельзя использовать вне холста

2023-12-20 12:36 UTC, bryzZz commented on src/renderer/src/components/Hierarchy/Hierarchy.tsx
> +    editor?.container.machineController.changeStateName(item.index.toString(), name);
А эти можно. Приложение общается с холстом через EditorManager и MachineController. Не хватает комментариев на этот счёт

2023-12-20 12:36 UTC, bryzZz commented on src/renderer/src/components/Hierarchy/Hierarchy.tsx
> +    tree.current?.expandAll();
Используется ControlledTreeEnvironment зачем тогда ещё и ref тыкать?

2023-12-20 12:36 UTC, bryzZz commented on src/renderer/src/components/Hierarchy/Hierarchy.tsx
> +            key="input"
key не нужен

2023-12-20 12:36 UTC, bryzZz commented on src/renderer/src/components/Hierarchy/Hierarchy.tsx
> +        <div>
В интерфейсе сделай всё в одну строчку

2023-12-20 12:36 UTC, bryzZz commented on src/renderer/src/components/Hierarchy/Hierarchy.tsx
> +                  className="flex h-10 w-full gap-3 rounded border-white bg-transparent pl-10 pr-2 text-current ring-2 focus:border-[#0c4bee] focus:outline-none focus:ring-2 focus:ring-[#0c4bee]"
Оторву руки, нельзя хардкодить цвета. В проекте уже есть стили для полей ввода. TextInput. Нужно расширить этот компонент чтобы можно было засунуть иконку

2023-12-20 12:36 UTC, bryzZz commented on src/renderer/src/components/Hierarchy/Hierarchy.tsx
> +                    setSearch(e.target.value);
Лишнее состояние. В функции find можно вытаскивать значение поля из объекта события (e)

2023-12-20 12:36 UTC, bryzZz commented on src/renderer/src/components/Hierarchy/Hierarchy.tsx
> +                  {...props}
Нужно перенести в начало пропсов

2023-12-20 12:36 UTC, bryzZz commented on src/renderer/src/components/Hierarchy/Hierarchy.tsx
> +            key="button1"
Убрать

2023-12-20 12:36 UTC, bryzZz commented on src/renderer/src/components/Hierarchy/Hierarchy.tsx
> +            key="button2"
Убрать

2023-12-20 12:36 UTC, bryzZz commented on src/renderer/src/components/Hierarchy/Hierarchy.tsx
> +                className="btn-primary mb-2 flex w-full items-center justify-center gap-3"
Лишние стили, можно btn-primary mb-2 w-full

2023-12-20 12:36 UTC, bryzZz commented on src/renderer/src/components/Sidebar/Explorer.tsx
> +      <div className="h-full flex-auto px-4 pt-3 text-center">
Нужно чтобы иерархия отлипла от компонентов

2023-12-20 12:36 UTC, bryzZz commented on src/renderer/src/hooks/useHierarchyManager.ts
> +          Object.entries(states)
Использовать вьюшки

2023-12-20 12:36 UTC, bryzZz commented on src/renderer/src/lib/data/EditorManager/EditorManager.ts
> +  //TODO: Выделение пока будет так работать, в дальнейшем требуется доработка
Не понятно какая доработка

2023-12-20 12:56 UTC, XidFanSan commented on src/renderer/src/lib/data/EditorManager/EditorManager.ts
> +  //TODO: Выделение пока будет так работать, в дальнейшем требуется доработка
Надо, чтобы react реагировал на selection не через EditorManager.ts, а придумать более гуманный способ для этой реализации. Вот и оставил комментарий, чтобы не забыть про это, так как выделение же никак к нужным данным не относится. Ты и сам понимаешь, потому что мы говорили об этом.

2023-12-20 13:00 UTC, XidFanSan commented on src/renderer/src/hooks/useHierarchyManager.ts
> +  const id: string | undefined = useMemo(() => {
Готово.

2023-12-25 12:54 UTC, chekoopa commented
Слишком долго, лью текущее положение, допиливайте отдельными PR.

2023-12-25 12:55 UTC, merged