Ошибки типов в параметрах компонентов
kruzhok-team/lapki-client pull request #170
Opened 2023-12-29 14:48 UTC by bryzZz

Что сделано:
- Добавлены ошибки типов в модалке редактирования компонентов
  - типы arduino, сделан ошибкой, есть практически у каждого параметра
  - массив возможных значений сделан выбором (ArduinoMicro PWM)
- Поля ввода (Select и input) приведены к одному стилю
- Добавлена автоматическая фокусировка на имени компонента при открытии модалки, чтобы можно было легко редактировать с клавиатуры
- Добавлен сброс параметров формы после закрытия. Был такой баг: открываешь модалку -> меняешь параметр -> нажимаешь кнопку "закрыть" -> открываешь модалку опять и параметр остаётся таким на который ты его поменял, и кажется что параметер изменился когда на самом деле нет

2023-12-29 17:12 UTC, chekoopa commented on src/renderer/src/utils/index.ts
> +  byte(value) {
Нужно будет аккуратно учесть знаковые типы.

2023-12-29 17:13 UTC, chekoopa commented on src/renderer/src/utils/index.ts
> +export const validators: Record<string, (value: string) => boolean> = {
Добавь сюда комментарий, зачем эта конструкция, чтобы потом проще было найти и добавить новые типы. Вообще.

2024-01-01 17:23 UTC, chekoopa requested changes
Учти эти два комментария, пожалуйста. Тогда сразу можно будет вмержить.

2024-01-02 09:42 UTC, bryzZz commented on src/renderer/src/utils/index.ts
> +  byte(value) {
byte не знаковый https://www.arduino.cc/reference/en/language/variables/data-types/byte/

2024-01-02 10:01 UTC, bryzZz commented on src/renderer/src/utils/index.ts
> +  byte(value) {
Я добавил пока все которые нашёл в платформах

2024-01-02 17:51 UTC, chekoopa approved these changes

2024-01-02 17:52 UTC, merged