Иерархия состояний
kruzhok-team/lapki-client pull request #206
Opened 2024-02-01 09:50 UTC by bryzZz

Что сделано:
- Рефакторинг
- Изменён поиск и вообще фильтры

Не знаю что случилось с package-lock.json я просто сделал npm i (возможно этот файл теперь проблемный, @chekoopa попробуй пожалйста удалить этот файл и node_modules и сделать npm i)
Вливать со сквошем

2024-02-09 14:44 UTC, chekoopa requested changes

2024-02-09 14:44 UTC, chekoopa commented on src/renderer/src/lib/data/StatesController.ts
> +    //Переносено с useDiagramContextMenu.ts, так как эта математика нужна лишь для событий внутри состояний
> переносено
> щас

Перепиши комментарий немного

2024-02-09 14:44 UTC, chekoopa commented on src/renderer/src/lib/data/EditorManager/Serializer.ts
> +    //Требуется проверка на удаление
Неясен смысл комментария

2024-02-09 14:44 UTC, chekoopa commented on src/renderer/src/lib/data/EditorManager/EditorManager.ts
> +  //TODO: Выделение пока будет так работать, в дальнейшем требуется доработка
Что за доработка?

2024-02-09 14:44 UTC, chekoopa commented on src/renderer/src/hooks/useFileOperations.ts
> +  const isStale = manager.useData('isStale');
Зачем перенос строки?

2024-02-09 14:44 UTC, chekoopa commented on src/renderer/src/hooks/useDiagramContextMenu.ts
> +      //Пришлось перетащить эту математику в контроллеры state и transition, так как контекстное меню теперь работает не только с редактором
«теперь» можно убрать, всё-таки важно текущее состояние

2024-02-09 14:44 UTC, chekoopa commented on src/renderer/src/components/UI/TextField.tsx
> +
Коротко описать смысл виджета (то же про TextInput). Особенно важно подчеркнуть разницу между ними.

2024-02-09 14:44 UTC, chekoopa commented on src/renderer/src/components/Hierarchy/InputRender.tsx
> +export const InputRender: React.FC<{ props }> = ({ props }) => {
Описать назначение.

2024-02-09 14:44 UTC, chekoopa commented on src/renderer/src/components/Hierarchy/TitleRender.tsx
> +export const TitleRender: React.FC<TitleRenderProps> = (props) => {
Описать назначение.

2024-02-09 14:44 UTC, chekoopa commented
LGTM, но нужно поправить комментарии и документирование.

2024-02-10 03:20 UTC, bryzZz commented on src/renderer/src/lib/data/StatesController.ts
> +    //Переносено с useDiagramContextMenu.ts, так как эта математика нужна лишь для событий внутри состояний
Он вообще не нужен

2024-02-10 03:21 UTC, bryzZz commented on src/renderer/src/lib/data/EditorManager/Serializer.ts
> +    //Требуется проверка на удаление
Мне тоже, удаляю

2024-02-10 03:21 UTC, bryzZz commented on src/renderer/src/lib/data/EditorManager/EditorManager.ts
> +  //TODO: Выделение пока будет так работать, в дальнейшем требуется доработка
Никакая

2024-02-10 03:21 UTC, bryzZz commented on src/renderer/src/hooks/useFileOperations.ts
> +  const isStale = manager.useData('isStale');
Бред

2024-02-10 03:21 UTC, bryzZz commented on src/renderer/src/hooks/useDiagramContextMenu.ts
> +      //Пришлось перетащить эту математику в контроллеры state и transition, так как контекстное меню теперь работает не только с редактором
Тоже не нужный коммент

2024-02-11 13:55 UTC, chekoopa approved these changes
LGTM

2024-02-11 13:56 UTC, merged