Доработка переключения страниц документации
kruzhok-team/lapki-client pull request #214
Opened 2024-02-06 12:25 UTC by bryzZz

Closes #213

2024-02-09 14:46 UTC, chekoopa commented on src/renderer/src/components/Documentation/Documentation.tsx
> +      console.warn(reason);
Выронил TODO про отразить ошибку в интерфейсе.

2024-02-09 14:48 UTC, chekoopa commented on src/renderer/src/components/Documentation/components/Navigation.tsx
> +        Назад
А не будет ли путаницы между переключением разделов и переходов по истории посещений?

2024-02-09 14:49 UTC, chekoopa requested changes
LGTM, но нужно поправить документирование и приложить скриншот.

2024-02-10 03:10 UTC, bryzZz commented on src/renderer/src/components/Documentation/components/Navigation.tsx
> +        Назад
Перенёс вниз

2024-02-11 14:17 UTC, chekoopa approved these changes
LGTM

2024-02-11 14:17 UTC, merged