Текстовый режим
kruzhok-team/lapki-client pull request #232
Opened 2024-03-05 06:01 UTC by bryzZz

Почти сделан UI

Closes #223

2024-06-17 19:43 UTC, chekoopa commented on demos/CyberiadaSchemas/CyberiadaFormat-Autoborder.graphml
> +lapkiVisual/ false
Берлоговские схемы визуальные же.

2024-06-19 05:15 UTC, chekoopa requested changes

2024-06-19 05:15 UTC, chekoopa commented on src/renderer/src/lib/drawable/Events.ts
> +      const textData = prepareText(text, this.parent.dimensions.width - 2 * 15, {
TODO: изменение параметров текста (общее для редактора)

2024-06-19 05:15 UTC, chekoopa commented on src/renderer/src/lib/drawable/TransitionNode/Label.ts
> +    ctx.fillStyle = 'rgb(23, 23, 23)';
TODO: когда-нибудь это ляжет в тему

2024-06-19 05:40 UTC, bryzZz commented on src/renderer/src/components/ComponentAddModal.tsx
> +              {visual && (
Если их не скрывать то весь редактор заполнояют иконки "отсутсвие иконки", мне показалось что это слишком

2024-06-19 05:44 UTC, bryzZz commented on src/renderer/src/components/NodeModal/ActionsModal/ActionsModal.tsx
> +export const ActionsModal: React.FC<ActionsModalProps> = ({
Внутри модалок редактирования состояний и переходов, этот блок называется "Делай", потому что там описываются действия. Мне показалось странным что блок в котором описываются действия называется "события"

2024-06-19 05:48 UTC, bryzZz commented on src/renderer/src/lib/drawable/Events.ts
> +      const text = serializeStateActions(
Нет, под капотом клиента хранится словарик, чтобы перевести в голый текст нужно пользоваться такой штукой. Или я не понял вопрос)

2024-06-19 07:17 UTC, bryzZz commented on src/renderer/src/components/ComponentAddModal.tsx
> +              {visual && (
Этот значек отсутсвия иконки как будто бы говорит об ошибке, хотя ее на самом деле нет

2024-06-20 12:17 UTC, chekoopa commented on src/renderer/src/components/NodeModal/ActionsModal/ActionsModal.tsx
> +export const ActionsModal: React.FC<ActionsModalProps> = ({
Если речь о действиях (добавь док-коммент, кстати), то такое переименование разумно.

2024-06-20 12:17 UTC, chekoopa commented on src/renderer/src/components/ComponentAddModal.tsx
> +              {visual && (
Странно, должно же нормальные значки отображать. А вот если значка нет, то уже не отображать.

2024-06-20 12:23 UTC, chekoopa commented on src/renderer/src/lib/drawable/Events.ts
> +      const text = serializeStateActions(
В смысле, в текстовом режиме действия – это голая строка с переносами.

2024-06-21 05:24 UTC, bryzZz commented on src/renderer/src/lib/drawable/Events.ts
> +      const text = serializeStateActions(
Вот так может выглядеть trigger на клиенте в текстовом режиме:
- { component: "button", method: "onPressed", args: {} }
- "mySupapupaTrigger()"

Первый вариант выбирался через селект, второй был написан вручную

2024-06-21 05:57 UTC, bryzZz commented on src/renderer/src/components/ComponentAddModal.tsx
> +              {visual && (
![Screenshot from 2024-06-21 13-56-46](https://github.com/kruzhok-team/lapki-client/assets/73271787/08ef09ca-483b-4d5d-bf02-fda36e090fbb)
![Screenshot from 2024-06-21 13-56-57](https://github.com/kruzhok-team/lapki-client/assets/73271787/c9e605dd-1fc4-45ba-bf6f-d75b8fc9f1fb)

Это плохо

2024-06-22 10:07 UTC, chekoopa commented on src/renderer/src/lib/drawable/Events.ts
> +      const text = serializeStateActions(
Я о том, что бы над текстовым представлением лишние действия на каждой перерисовке не делались.

2024-06-22 10:11 UTC, chekoopa commented on src/renderer/src/components/ComponentAddModal.tsx
> +              {visual && (
Пустой отступ напрашивается. Но тогда что делать, если у всех значков нет...
Может, стандартный нейтральный значок? Не «значок не найден», а такой контурно-незврачный значок, треугольник или квадрат...

2024-06-22 15:11 UTC, bryzZz commented on src/renderer/src/components/ComponentAddModal.tsx
> +              {visual && (
Зачем нужен значек если он ничего не делает? Мне все еще кажется что просто текст - это самый лучшый вариант

2024-06-22 19:13 UTC, chekoopa commented on src/renderer/src/components/ComponentAddModal.tsx
> +              {visual && (
Ну как ничего не делает. При наличии обозначение – визуально отличает компонент от других. В отсутствие – базовый значок служит маркером списка.

2024-06-26 16:21 UTC, chekoopa requested changes
Дежурное напоминание, что есть незакрытый вопрос

2024-07-04 01:02 UTC, merged