Проверка и обработка наличия avrdude
kruzhok-team/lapki-client pull request #251
Opened 2024-03-26 13:01 UTC by Roundabout1

Вывод сообщения и кнопки, если avrdude не найден

2024-05-05 16:21 UTC, chekoopa commented
Инструкцию по установке тоже можно в вики положить.

2024-06-05 12:00 UTC, Roundabout1 commented
Если загрузчик не может найти avrdude, то появляется такая кнопка, она отсутствует, если всё в порядке
![image](https://github.com/kruzhok-team/lapki-client/assets/86153878/7b78cc49-426f-4fff-acde-c1adc4db2988)

2024-06-05 12:01 UTC, Roundabout1 commented
При нажатии на кнопку появляется модалка, ссылка ведёт на [вики](https://github.com/kruzhok-team/lapki-flasher/wiki/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-AVRDUDE)
![image](https://github.com/kruzhok-team/lapki-client/assets/86153878/b121c779-c432-4870-ac6c-28614f0a97b9)

2024-06-06 09:13 UTC, chekoopa commented on src/renderer/src/components/AvrdudeGuide.tsx
> +        , чтобы узнать как установить и добавить avrdude.
`чтобы узнать, как`

2024-06-06 09:18 UTC, chekoopa requested changes

2024-06-06 09:18 UTC, chekoopa commented on src/renderer/src/components/Sidebar/Loader.tsx
> +          <button type="button" className="btn-primary mb-2 w-full" onClick={openAvrdudeGuideModal}>
Лучше переместить наверх и поставить фон красного цвета. 

@bryzZz может подскажет.

2024-06-06 14:47 UTC, bryzZz commented on src/main/modules/ModuleManager.ts
> +              console.log('AVRDUDE TRUE');
Убрать

2024-06-06 14:47 UTC, bryzZz commented on src/main/modules/ModuleManager.ts
> +              });
Чего?
const path = await lookpath('avrdude');
и тут с ним что-то делай

2024-06-06 14:47 UTC, bryzZz commented on src/main/settings.ts
> +    avrdude: false,
hasAvrdude или haveAvrdude, в общем надо назвать как-то нормально

2024-06-06 14:47 UTC, bryzZz commented on src/renderer/src/components/AvrdudeGuide.tsx
> +  const guideRef =
Вынести за компонент

2024-06-06 14:47 UTC, bryzZz commented on src/renderer/src/components/Sidebar/Loader.tsx
> +          <button type="button" className="btn-primary mb-2 w-full" onClick={openAvrdudeGuideModal}>
Добавь в тему warning цвет и заюзай. Нужно потрогать tailwind.config.js и src/renderer/src/theme.ts

2024-06-06 14:47 UTC, bryzZz commented on src/renderer/src/components/Sidebar/Loader.tsx
> +        <div>
Зачем этот div?

2024-06-07 06:51 UTC, Roundabout1 commented on src/renderer/src/components/Sidebar/Loader.tsx
> +        <div>
он был лишним, сейчас удалён

2024-06-07 07:17 UTC, Roundabout1 commented on src/renderer/src/components/Sidebar/Loader.tsx
> +          <button type="button" className="btn-primary mb-2 w-full" onClick={openAvrdudeGuideModal}>
Взял цвет warning с [сайта Tailwind](https://tw-elements.com/docs/standard/content-styles/colors/). Кнопка выглядит вот так:
![image](https://github.com/kruzhok-team/lapki-client/assets/86153878/a058f6a6-25e3-4811-bab2-de7221af5a80)
И на светлой теме:
![image](https://github.com/kruzhok-team/lapki-client/assets/86153878/79a7de8c-7159-47ec-b131-2e4c942ce593)
Это один и тот же цвет на две темы, не знаю стоит ли его делать разным для каждой темы.

2024-06-07 08:27 UTC, chekoopa commented on src/renderer/src/components/AvrdudeGuide.tsx
> +        Не забудьте <b>перзагрузить</b> IDE после установки и настройки avrdude!
Загрузчик не может найти программу Avrdude на вашем устройстве. Она необходима для того, чтобы прошивать некоторые устройства (например, Arduino). 

Обратитесь к [инструкции](https://github.com/kruzhok-team/lapki-flasher/wiki/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-AVRDUDE), чтобы узнать, как правильно установить и настроить Avrdude.

И не забудьте **перезапустить** IDE после установки и настройки Avrdude!

2024-06-07 09:08 UTC, bryzZz commented on src/main/modules/ModuleManager.ts
> +// импорт старой версии (3.0 вместо 4.0), так как новая версия требует ESM
так старого импорта нет, зачем этот коммент?

2024-06-07 09:08 UTC, bryzZz commented on src/main/modules/ModuleManager.ts
> +                settings.set(AVRDUDE_SETTING, false);
settings.set(AVRDUDE_SETTING, Boolean(path));

2024-06-07 09:08 UTC, bryzZz commented on src/renderer/src/theme.ts
> +  'bg-warning': '--bg-w',
Просто warning как primary

2024-06-07 09:08 UTC, bryzZz commented on src/renderer/src/components/Sidebar/Loader.tsx
> +    return;
```typescript
if (!(flasherIsLocal && !hasAvrdude)) return;
return (
        <button
          type="button"
          className="btn-primary mb-2 w-full border-bg-warning bg-bg-warning"
          onClick={openAvrdudeGuideModal}
        >
          Программа avrdude не найдена!
        </button>
      );
```

2024-06-10 05:22 UTC, Roundabout1 commented on src/main/modules/ModuleManager.ts
> +// импорт старой версии (3.0 вместо 4.0), так как новая версия требует ESM
комментарий относится к 'fix-path', видимо при слиянии он улетел вниз, я вернул его на место

2024-06-10 05:51 UTC, bryzZz approved these changes

2024-06-10 10:09 UTC, chekoopa approved these changes

2024-06-10 10:12 UTC, merged