Изменение блока документации и код для определения Avrdude.
kruzhok-team/lapki-client pull request #265
Opened 2024-04-23 09:42 UTC by XidFanSan

2024-04-24 08:26 UTC, bryzZz commented on src/main/settings.ts
> +    net: true,
grid

2024-04-24 08:26 UTC, bryzZz commented on src/renderer/src/components/Documentation/Documentation.tsx
> +    if (width < 840) {
Автоматические расширение при выборе?

2024-04-24 08:26 UTC, bryzZz commented on src/renderer/src/components/Documentation/Documentation.tsx
> +        topOffset && 'top-[44.19px] h-[95.85vh]'
Это зачем?

2024-04-24 08:26 UTC, bryzZz commented on src/renderer/src/components/Sidebar/Setting.tsx
> +            Сетка редактора
Это же должно быть в блоке изменения зума

2024-04-24 08:30 UTC, XidFanSan commented on src/renderer/src/components/Documentation/Documentation.tsx
> +        topOffset && 'top-[44.19px] h-[95.85vh]'
Упростил вид кода, но это сделано было чтобы блок документации смещался по высоте, когда вкладки появляются.

2024-04-24 08:32 UTC, XidFanSan commented on src/renderer/src/components/Sidebar/Setting.tsx
> +            Сетка редактора
Так мы же определились в настройки кнопку добавить, а если пользователю надо будет, то через комбинацию клавиш может выключить/включить сетку, но комбинация ещё не готова, так как я не знаю на какую комбинацию будет сетка реагировать.

2024-04-24 08:32 UTC, XidFanSan commented on src/main/settings.ts
> +    net: true,
Понял

2024-04-24 08:32 UTC, XidFanSan commented on src/renderer/src/components/Documentation/Documentation.tsx
> +    if (width < 840) {
Это как?

2024-04-24 08:40 UTC, bryzZz commented on src/renderer/src/components/Sidebar/Setting.tsx
> +            Сетка редактора
Мы как раз определили с тем что это будет в блоке зума

2024-04-24 08:41 UTC, bryzZz commented on src/renderer/src/components/Documentation/Documentation.tsx
> +    if (width < 840) {
Что делает этот блок кода?

2024-04-24 08:42 UTC, bryzZz commented on src/renderer/src/components/Documentation/Documentation.tsx
> +        topOffset && 'top-[44.19px] h-[95.85vh]'
А высота вкладок зависит от vh?

2024-04-24 12:53 UTC, XidFanSan commented on src/renderer/src/components/Documentation/Documentation.tsx
> +    if (width < 840) {
Иначе в документации будет показан лишь блок "Содержание"

2024-04-24 12:53 UTC, XidFanSan commented on src/renderer/src/components/Documentation/Documentation.tsx
> +        topOffset && 'top-[44.19px] h-[95.85vh]'
Нет

2024-04-24 13:06 UTC, bryzZz commented on src/renderer/src/components/Documentation/Documentation.tsx
> +        topOffset && 'top-[44.19px] h-[95.85vh]'
нужно вернуть обрано, на разных экранах не будет работать

2024-04-24 15:49 UTC, XidFanSan commented on src/renderer/src/components/Documentation/Documentation.tsx
> +        topOffset && 'top-[44.19px] h-[95.85vh]'
Ок

2024-04-27 11:21 UTC, chekoopa commented on resources/platform/Stapler.json
> +          "description": "Модуль предоставляет вооружение (ближнего или дальнего боя), которым можно атаковать конкретную цель. Цель определяется через модуль сенсора, а модуль вооружения позволяет о
Зачем? :thinking:

2024-04-27 11:23 UTC, chekoopa commented on src/renderer/src/components/Scale.tsx
> +      animations: canvasSettings?.animations ?? false,
```ts
{
  canvasSettings..., 
  grid: !canvasSettings?.grid
}
```
@bryzZz Так лучше будет?

2024-04-27 11:37 UTC, chekoopa commented on src/renderer/src/components/Sidebar/Setting.tsx
> +    setCanvasSettings({ animations: value, grid: canvasSettings?.grid ?? false });
```ts
{
  canvasSettings..., 
  grid: canvasSettings?.grid ?? false
}
```
@bryzZz Так лучше будет?

2024-04-27 12:14 UTC, bryzZz commented on src/renderer/src/components/Scale.tsx
> +      animations: canvasSettings?.animations ?? false,
Да

2024-04-27 12:14 UTC, bryzZz commented on src/renderer/src/components/Sidebar/Setting.tsx
> +    setCanvasSettings({ animations: value, grid: canvasSettings?.grid ?? false });
да

2024-04-27 12:33 UTC, XidFanSan commented on resources/platform/Stapler.json
> +          "description": "Модуль предоставляет вооружение (ближнего или дальнего боя), которым можно атаковать конкретную цель. Цель определяется через модуль сенсора, а модуль вооружения позволяет о
Он не работал и тег <i> вместе с текстом показывался в IDE, поэтому решил вообще убрать этот тег.

2024-04-27 12:51 UTC, chekoopa requested changes
Нужно внести две правки из комментариев (где отписались мы с Никитой).

2024-04-27 13:10 UTC, chekoopa approved these changes

2024-04-27 13:48 UTC, merged