Редизайн блока документации.
kruzhok-team/lapki-client pull request #268
Opened 2024-04-30 10:12 UTC by XidFanSan

1) Удалён лишний код;
2) Добавлено расширение/сжатие блока документации;
3) Добавлена кнопка открытия документации с иконкой вопроса;
4) Когда открыта схема, кнопка перемещается в область изменения зума редактора;
5) Убраны отдельные вкладки, теперь содержание с просмотром документации будет совместный;
6) При двойном клике на блок документации оно будет закрываться.

2024-05-01 09:43 UTC, chekoopa commented
Приложи скриншоты, пожалуйста.

2024-05-01 13:20 UTC, XidFanSan commented
https://github.com/kruzhok-team/lapki-client/assets/135246322/e6d719f3-d19e-483e-a5ee-fa7a13cd58d0

2024-05-01 16:26 UTC, chekoopa commented
> Убраны отдельные вкладки, теперь содержание с просмотром документации будет совместный;

Неудачное решение кмк, дерево слишком много экранного пространства забирает, поэтому и делали двумя вкладками.

2024-05-02 04:20 UTC, bryzZz requested changes

2024-05-02 04:20 UTC, bryzZz commented on src/renderer/src/components/Documentation/Documentation.tsx
> +        className={twMerge('border-l border-border-primary bg-bg-secondary')}
twMerge тут не нужен

2024-05-02 04:20 UTC, bryzZz commented on src/renderer/src/assets/icons/question.svg
Что это за цвет? Нужно использовать primary из темы

2024-05-02 09:58 UTC, XidFanSan commented on src/renderer/src/assets/icons/question.svg
Мне такой дали и сказали оставить)

2024-05-02 09:59 UTC, XidFanSan commented on src/renderer/src/components/Documentation/Documentation.tsx
> +        className={twMerge('border-l border-border-primary bg-bg-secondary')}
Забыл видимо удалить

2024-05-03 12:22 UTC, closed without merging