Добавление кнопок для загрузчика и компилятора.
kruzhok-team/lapki-client pull request #285
Opened 2024-05-03 13:50 UTC by XidFanSan

1) Была добавлена кнопка настройки адреса компилятора в разделе компилятора на боковой панели (такая же была в загрузчике);
2) Была добавлена кнопка настройки адреса загрузчика в разделе настройки на боковой панели;
3) Были исправлены мелкие недочёты в тексте ошибок в классе Flasher;
4) Были изменены и добавлены стили в файле загрузчика.

2024-05-05 13:36 UTC, chekoopa requested changes

2024-05-05 13:36 UTC, chekoopa commented on src/renderer/src/components/Modules/Flasher.ts
> +            this.setFlasherLog('Не удалось распарсить JSON-сообщение от клиента.');
`Не удалось прочесть запрос от клиента (возможно, конфликт версий)`

2024-05-05 13:36 UTC, chekoopa commented on src/renderer/src/components/Modules/Flasher.ts
> +            this.setFlasherLog('Получены бинарные данных, хотя запроса на прошивку не было.');
`Получен файл, хотя процесс прошивки не запускался`

2024-05-05 13:36 UTC, chekoopa commented on src/renderer/src/components/Sidebar/Setting.tsx
> +  const [isFlasherOpen, openFlasher, closeFlasher] = useModal(false);
Я правильно понимаю, что у нас теперь по два экземпляра модального окна настроек для каждого модуля? Можем ли мы это как-то исправить?

Это не к тому, что нужно исправлять, сейчас это вопрос на размышление.

2024-05-05 13:36 UTC, chekoopa commented on src/renderer/src/components/Sidebar/Loader.tsx
> -              flasherIsLocal && connectionStatus == FLASHER_CONNECTING && 'opacity-70'
Зачем убрано переключение стилей?

2024-05-05 13:36 UTC, chekoopa commented on src/renderer/src/components/Sidebar/Loader.tsx
> +  const [isFlasherOpen, openFlasher, closeFlasher] = useModal(false);
Лучше поменять название этих переменных, чтобы не вводило в заблуждение.  `Flasher -> FlasherSettings`

2024-05-05 13:36 UTC, chekoopa commented on src/renderer/src/components/Sidebar/Compiler.tsx
> +  const [isCompilerOpen, openCompiler, closeCompiler] = useModal(false);
Лучше поменять название этих переменных, чтобы не вводило в заблуждение. 
`Compiler -> CompilerSettings`

2024-05-05 13:47 UTC, XidFanSan commented on src/renderer/src/components/Modules/Flasher.ts
> +            this.setFlasherLog('Не удалось распарсить JSON-сообщение от клиента.');
Хмм

2024-05-05 13:48 UTC, XidFanSan commented on src/renderer/src/components/Modules/Flasher.ts
> +            this.setFlasherLog('Получены бинарные данных, хотя запроса на прошивку не было.');
Готово.

2024-05-05 13:48 UTC, XidFanSan commented on src/renderer/src/components/Modules/Flasher.ts
> +            this.setFlasherLog('Не удалось распарсить JSON-сообщение от клиента.');
Готово.

2024-05-05 13:50 UTC, XidFanSan commented on src/renderer/src/components/Sidebar/Setting.tsx
> +  const [isFlasherOpen, openFlasher, closeFlasher] = useModal(false);
Получается так, если что, то обсудим на неделе, чтобы сразу закрыть этот вопрос.

2024-05-05 13:52 UTC, XidFanSan commented on src/renderer/src/components/Sidebar/Loader.tsx
> -              flasherIsLocal && connectionStatus == FLASHER_CONNECTING && 'opacity-70'
Данное условие стоит и на disabled, поэтому кнопка блокируется точно при том же условии и менять прозрачность было лишним.

2024-05-05 13:54 UTC, XidFanSan commented on src/renderer/src/components/Sidebar/Compiler.tsx
> +  const [isCompilerOpen, openCompiler, closeCompiler] = useModal(false);
Готово.

2024-05-05 13:56 UTC, XidFanSan commented on src/renderer/src/components/Sidebar/Loader.tsx
> +  const [isFlasherOpen, openFlasher, closeFlasher] = useModal(false);
Готово.

2024-05-07 07:11 UTC, bryzZz requested changes
Не нужно обьявлять одну и ту же модалку в разных местах. Это огромное пространство для багов с синхронизацией данных. Нужно вынести их в общего родителя и передавать функции управения вниз

2024-05-14 14:08 UTC, bryzZz commented on src/renderer/src/components/Sidebar/Setting.tsx
> +          disabled={connectionStatus == FLASHER_CONNECTING || flashing}
===

2024-05-14 14:08 UTC, bryzZz commented on src/renderer/src/components/Sidebar/Setting.tsx
> +          disabled={connectionStatus == FLASHER_CONNECTING || flashing}
(connectionStatus == FLASHER_CONNECTING) || flashing если я правильно понял логику

2024-05-14 14:08 UTC, bryzZz commented on src/renderer/src/components/Sidebar/Loader.tsx
> +          disabled={flashResult == undefined}
===

2024-05-14 14:08 UTC, bryzZz commented on src/renderer/src/components/Sidebar/Loader.tsx
> +            className={flasherFile ? 'btn-primary mb-2 px-4' : 'btn-primary mb-2 px-4 opacity-70'}
Тут надо twMerge использовать

2024-05-15 05:37 UTC, XidFanSan commented on src/renderer/src/components/Sidebar/Compiler.tsx
> +            {compilerStatus != 'Не подключен' ? 'Скомпилировать' : 'Переподключиться'}
Готово.

2024-05-16 13:24 UTC, bryzZz approved these changes

2024-05-18 12:43 UTC, chekoopa approved these changes

2024-05-18 12:44 UTC, merged