Исправление ошибки подключения к локальному загрузчику
kruzhok-team/lapki-client pull request #287
Opened 2024-05-07 12:08 UTC by Roundabout1

Исправление сразу двух багов: отсутствие подключение к локальному загрузчику при первом запуске IDE (когда значения в electron-settings заданы по-умолчанию)  и невозможность при этом снова подключиться через перезапуск локального загрузчика.
Является решением этой проблемы: https://github.com/kruzhok-team/lapki-client/issues/286

2024-05-07 12:17 UTC, Roundabout1 commented
Нашлась ошибка

2024-05-07 12:44 UTC, Roundabout1 commented
Ошибка исправлена

2024-05-07 15:34 UTC, bryzZz requested changes

2024-05-07 15:34 UTC, bryzZz commented on src/renderer/src/components/Sidebar/Loader.tsx
> +      setFlasherSetting({ ...flasherSetting, ...{ port: localPort } }).then(() => {
if (type === 'local' && port !== localPort) {
      setFlasherSetting({ ...flasherSetting, port: localPort }).then(() => {

2024-05-08 06:09 UTC, Roundabout1 commented on src/renderer/src/components/Sidebar/Loader.tsx
> +      setFlasherSetting({ ...flasherSetting, ...{ port: localPort } }).then(() => {
Исправлено

2024-05-13 06:32 UTC, closed without merging