Кнопка сброса всех настроек
kruzhok-team/lapki-client pull request #289
Opened 2024-05-08 09:14 UTC by Roundabout1

https://github.com/kruzhok-team/lapki-client/issues/288

2024-05-15 12:58 UTC, Roundabout1 commented
Не подключается к загрузчику после сброса, из-за проблемы, описанной здесь: https://github.com/kruzhok-team/lapki-client/issues/286. Желательно сначала вмержить этот [PR](https://github.com/kruzhok-team/lapki-client/pull/292), чтобы исправить эту проблему.

2024-05-28 04:35 UTC, chekoopa requested changes
И конфликт слияния почини тоже.

2024-05-28 04:35 UTC, chekoopa commented on src/renderer/src/components/ResetSettingsModal.tsx
> +      на кнопку "{RESET_LABEL}" IDE перезапуститься, а все значения настроек вернутся к изначальным.
ться/тся
И предупреждение о возможно не сохранённых файлах.

2024-05-28 08:32 UTC, chekoopa requested changes
Вмержил запрошенный тобой PR, нужно починить небольшой конфликт.

2024-05-28 08:32 UTC, chekoopa commented on src/renderer/src/components/ResetSettingsModal.tsx
> +      несохранённые изменения в схеме будут утеряны!
Лучше выдели жирным.

2024-05-28 11:48 UTC, Roundabout1 commented on src/renderer/src/components/ResetSettingsModal.tsx
> +      несохранённые изменения в схеме будут утеряны!
всё выделить или лучше по-частям как на скриншоте?
![image](https://github.com/kruzhok-team/lapki-client/assets/86153878/9f041607-475f-4198-bdc7-a855b4ab01de)

2024-05-30 02:26 UTC, bryzZz approved these changes

2024-05-30 09:33 UTC, merged