Редизайн блока документации.
kruzhok-team/lapki-client pull request #290
Opened 2024-05-13 03:44 UTC by XidFanSan

1) Осталось сделать так, чтобы блок изменения зума смещался на необходимое расстояние от блока документации.

2024-05-14 14:19 UTC, bryzZz requested changes
![Screenshot from 2024-05-14 22-18-49](https://github.com/kruzhok-team/lapki-client/assets/73271787/e36519ff-685f-4a38-b8ce-f75cd443af89)

У меня что-то все поехало

2024-05-14 14:19 UTC, bryzZz commented on src/renderer/src/components/Documentation/Documentation.tsx
> +            <Question height={40} width={40} />
Вот тут нужно передавать основной цвет из темы, потому что он может меняться

2024-05-14 14:19 UTC, bryzZz commented on src/renderer/src/components/EditorSettings.tsx
> +  toggle: () => void;
onDocumentationToggle

2024-05-15 02:59 UTC, XidFanSan commented on src/renderer/src/components/EditorSettings.tsx
> +  toggle: () => void;
Исправлено.

2024-05-15 03:04 UTC, XidFanSan commented on src/renderer/src/components/Documentation/Documentation.tsx
> +            <Question height={40} width={40} />
Принял

2024-05-16 13:09 UTC, bryzZz commented on src/renderer/src/components/Documentation/Documentation.tsx
> +            <Question height={40} width={40} />
внутри Question сделать fill="currentColor", а button дать класс text-primary. Так многоие икнонки на проект сделаны, поищи

2024-05-16 13:12 UTC, bryzZz requested changes

2024-05-16 13:12 UTC, bryzZz commented on src/renderer/src/components/Documentation/Documentation.tsx
> +              activeTab === 0 && 'bg-primary text-white'
Нужно брать цвета из темы, text-text-primary

2024-05-16 13:12 UTC, bryzZz commented on src/renderer/src/components/Documentation/Documentation.tsx
> +              activeTab === 1 && 'bg-primary text-white'
Нужно брать цвета из темы, text-text-primary

2024-05-16 15:49 UTC, XidFanSan commented on src/renderer/src/components/Documentation/Documentation.tsx
> +            <Question height={40} width={40} />
Ну ничего не изменилось от слова совсем

2024-05-16 15:49 UTC, XidFanSan commented on src/renderer/src/components/Documentation/Documentation.tsx
> +            <Question height={40} width={40} />
Но сделаю, так уж и быть

2024-05-16 15:50 UTC, XidFanSan commented on src/renderer/src/components/Documentation/Documentation.tsx
> +              activeTab === 0 && 'bg-primary text-white'
Не работает, он цвет текста при светлой теме делает черным у выделенной вкладки.
![image](https://github.com/kruzhok-team/lapki-client/assets/135246322/576085dc-c265-4b25-b666-b8f8b3a0800b)

2024-05-17 03:47 UTC, bryzZz commented on src/renderer/src/components/Documentation/Documentation.tsx
> +              activeTab === 0 && 'bg-primary text-white'
text-text-secondary. В фигме есть все цвета

2024-05-17 03:50 UTC, XidFanSan commented on src/renderer/src/components/Documentation/Documentation.tsx
> +              activeTab === 0 && 'bg-primary text-white'
Исправлено.

2024-05-28 11:35 UTC, bryzZz requested changes
Все едет на разрешении 1920:1080
![Screenshot from 2024-05-28 19-33-52](https://github.com/kruzhok-team/lapki-client/assets/73271787/01645a8a-7dbf-4f11-9691-fb27006f170b)

2024-05-28 11:35 UTC, bryzZz commented on src/renderer/src/components/Documentation/Documentation.tsx
> +            <Question height={40} width={40} fill="currentColor" />
Внутри файла svg, там где ты сейчас сделал fill на основной цвет, нужно поменять на currentColor

2024-05-29 03:01 UTC, XidFanSan commented on src/renderer/src/components/Documentation/Documentation.tsx
> +            <Question height={40} width={40} fill="currentColor" />
Щас вообще не понял где что поменять.... 
Если я меняю в самом svg-файле цвет на currentColor то эта иконка при смене темы меняет цвет фиг знает как.
Поэтому я ничего менять не буду уже у этой иконки, а после когда зальем ты уже сам подправишь как тебе надо.

2024-05-29 04:26 UTC, XidFanSan reviewed
Исправлено, описание проблемы в коммите.

2024-05-30 02:18 UTC, bryzZz requested changes

2024-05-30 02:18 UTC, bryzZz commented on src/renderer/src/assets/icons/question.svg
> +    <path style="fill:#0c4bee;" d="M496.158,248.085c0-137.022-111.069-248.082-248.075-248.082C111.07,0.003,0,111.063,0,248.085 c0,137.001,111.07,248.07,248.083,248.07C385.089,496.155,496.158,385.086,
вот конкретно тут нужно поставил fill currentColor

2024-05-30 02:18 UTC, bryzZz commented on src/renderer/src/components/Documentation/Documentation.tsx
> +        'absolute right-0 top-0 flex',
absolute right-0 top-0 flex h-full

2024-05-30 02:18 UTC, bryzZz commented on src/renderer/src/components/Documentation/Documentation.tsx
> +        maxHeight={topOffset ? 'calc(100vh - 44.19px)' : '100vh'}
Удалить

2024-05-30 02:18 UTC, bryzZz commented on src/renderer/src/components/Documentation/Documentation.tsx
> +        size={{ width: width, height: '100vh' }}
size={{ width: width, height: '100%' }}

2024-05-30 09:37 UTC, chekoopa commented on src/renderer/src/assets/icons/question.svg
> +    <path style="fill:#0c4bee;" d="M496.158,248.085c0-137.022-111.069-248.082-248.075-248.082C111.07,0.003,0,111.063,0,248.085 c0,137.001,111.07,248.07,248.083,248.07C385.089,496.155,496.158,385.086,
А на уровне реакта? Добавь отдельным комментом, пожалуйста.

2024-05-30 10:05 UTC, bryzZz commented on src/renderer/src/assets/icons/question.svg
> +    <path style="fill:#0c4bee;" d="M496.158,248.085c0-137.022-111.069-248.082-248.075-248.082C111.07,0.003,0,111.063,0,248.085 c0,137.001,111.07,248.07,248.083,248.07C385.089,496.155,496.158,385.086,
У нас сделано так:
1. Устанавливаешь fill currentColor в самом файле svg
2. Устанавливаешь цвет текста в контейнере иконки (ну или не устанавливаешь и он наследуется)
3. Готово

2024-05-30 10:07 UTC, bryzZz requested changes

2024-05-30 10:07 UTC, bryzZz commented on src/renderer/src/components/EditorSettings.tsx
> +      <button className="px-2 outline-none hover:bg-bg-hover active:bg-bg-active" onClick={toggle}>
Тут text-primary чтобы иконка подхватила

2024-06-05 03:50 UTC, bryzZz approved these changes

2024-06-05 10:01 UTC, merged