Связь для комментариев.
kruzhok-team/lapki-client pull request #291
Opened 2024-05-14 04:45 UTC by XidFanSan

ЕСТЬ ПРОБЛЕМА - Связь идет вместе с условием, поэтому требуется доработать логику.

2024-05-18 13:55 UTC, bryzZz requested changes
DiagramEditor сломался и вроже бы нужно доделать иерархию

2024-05-18 13:55 UTC, bryzZz commented on src/renderer/src/lib/data/EditorController/TransitionsController.ts
>      const sourceState = this.controller.states.get(source);
```typescript
const source = this.controller.states.get(source) || this.controller.notes.get(source);
const target = this.controller.states.get(target) || this.controller.notes.get(target) || this.controller.transitions.get(target);
```

Так будет последовательно проверяться и попадет в одну переменную и не будет нужно кучу разных позиций учитывать

2024-05-18 13:55 UTC, bryzZz commented on src/renderer/src/lib/data/EditorController/TransitionsController.ts
> +      console.log(target);
У тебя eslint не подчеркивает console.log?

2024-05-18 13:55 UTC, bryzZz commented on src/renderer/src/lib/drawable/GhostTransition.ts
> +
```typescript
setSource(value: State | Note) {
  this.source = value;
}
```

2024-05-18 13:55 UTC, bryzZz commented on src/renderer/src/lib/drawable/Transition.ts
> +      //throw new Error(`State with id ${this.data.source} does not exist`);
Че, а если note не нашлась. Typescript же правильно подсказывает а ты отключаешь его с помощью ! ...........................................................................

```typescript
const node = this.app.controller.states.get(this.data.source) || this.app.controller.notes.get(this.data.source);
```

2024-05-18 13:55 UTC, bryzZz commented on src/renderer/src/lib/drawable/Transition.ts
> +      //throw new Error(`State with id ${this.data.target} does not exist`);
Тоже самое..............................
```typescript
const node = this.app.controller.states.get(this.data.source) || this.app.controller.notes.get(this.data.source) || this.app.controller.transitions.get(this.data.target);
```

2024-05-20 03:06 UTC, XidFanSan commented on src/renderer/src/lib/data/EditorController/TransitionsController.ts
> +      console.log(target);
Подчеркивает

2024-05-20 03:18 UTC, XidFanSan commented on src/renderer/src/lib/data/EditorController/TransitionsController.ts
>      const sourceState = this.controller.states.get(source);
Из-за одинаковых названий переменных он указывает на ошибку.

2024-05-20 03:19 UTC, XidFanSan commented on src/renderer/src/lib/data/EditorController/TransitionsController.ts
>      const sourceState = this.controller.states.get(source);
А если меняю название здесь "const { source, target, color, id: prevId, label } = params;" или в том коде, что ты скинул, то он указывает уже на ошибку типа.

2024-06-02 13:46 UTC, chekoopa commented on src/renderer/src/components/Hierarchy/Hierarchy.tsx
> +        data: { title: note.text ?? 'Комментарий', type: 'note' },
TODO: надо добавить название заметки (title)

2024-06-02 13:47 UTC, chekoopa commented on src/renderer/src/components/DiagramEditor.tsx
> +    source: State | ChoiceState | Note;
Чем больше этих типов в объединении, тем сильнее желание добавить тип-алиас и на источник, и на цель.

2024-06-02 15:45 UTC, chekoopa commented on src/renderer/src/lib/data/EditorController/TransitionsController.ts
> +    const targetId =
TODO: где-то должна быть проверка, что цель может быть не-состоянием, только если источник – заметка. Но это потом.

2024-06-04 05:08 UTC, XidFanSan commented on src/renderer/src/components/DiagramEditor.tsx
> +    source: State | ChoiceState | Note;
Были удалены многие типы, так как они и не требовались вовсе.

2024-06-09 12:08 UTC, bryzZz requested changes

2024-06-09 12:08 UTC, bryzZz commented on src/renderer/src/types/diagram.ts
> +    transitionLine: TransitionLine;
Зачем это хранится в данных?

2024-06-09 12:08 UTC, bryzZz commented on src/renderer/src/lib/drawable/TransitionNode/Transition.ts
> +  }
Это нужно вынести в utils

2024-06-09 12:08 UTC, bryzZz commented on src/renderer/src/lib/drawable/TransitionNode/Transition.ts
> +      transitionLine ?? {
getLine может вернуть undefined? Зачем тет эти два вопросика?

2024-06-09 12:08 UTC, bryzZz commented on src/renderer/src/lib/data/EditorController/StatesController.ts
> +    this.emit('mouseUpOnInitialState', state);
Это событие нигде не используется

2024-06-09 12:08 UTC, bryzZz commented on src/renderer/src/lib/drawable/TransitionNode/ArrowsWithLabel.ts
> + * Выполняет отрисовку стрелки между двумя(тремя) движущимися блоками:
"двумя(тремя)" че?

2024-06-09 12:08 UTC, bryzZz commented on src/renderer/src/lib/drawable/TransitionNode/ArrowsWithoutLabel.ts
> + * Выполняет отрисовку стрелки между двумя(тремя) движущимися блоками:
двумя(тремя) опять не понятно

2024-06-10 07:20 UTC, XidFanSan commented on src/renderer/src/types/diagram.ts
> +    transitionLine: TransitionLine;
Было убрано из данных, так как работает и без этого.

2024-06-10 07:41 UTC, XidFanSan commented on src/renderer/src/lib/drawable/TransitionNode/Transition.ts
> +      transitionLine ?? {
get полностью удален, вместе с set, так как и без них все оказывается работает.

2024-06-11 09:49 UTC, chekoopa commented on src/renderer/src/lib/data/EditorController/NotesController.ts
> +    this.controller.transitions.forEachByStateId(id, (transition) => {
Это точно удаляет переходы и от заметки, и к заметке?

2024-06-13 03:29 UTC, chekoopa requested changes
Обнови ветку и устрани конфликт

2024-06-13 03:29 UTC, bryzZz approved these changes

2024-06-13 03:49 UTC, chekoopa approved these changes

2024-06-13 03:51 UTC, merged