Интеграция с модулем компилятора
kruzhok-team/lapki-client pull request #307
Opened 2024-05-31 05:30 UTC by L140-beep

2024-06-02 13:37 UTC, chekoopa requested changes

2024-06-02 13:37 UTC, chekoopa commented on electron.vite.config.1715498763739.mjs
Откуда эти файлы? Не протечка ли?

2024-06-02 13:37 UTC, chekoopa commented on src/renderer/src/components/Modules/Compiler.ts
>          case 'ArduinoUno': {
А нужен ли теперь `switch` в таком виде? В смысле, почему бы не обрабатывать особые варианты (типа импорта берлоговской схемы), а на `default` уже отправлять `cgml` в компилятор?

2024-06-02 13:37 UTC, chekoopa commented on src/renderer/src/lib/data/GraphmlBuilder.ts
> +      platformVersion: '1.0',
Это точно нужно класть в файл платформы и пробрасывать из него.

2024-06-02 13:37 UTC, chekoopa commented on src/renderer/src/lib/data/GraphmlBuilder.ts
> +  const isArduino = platform.name?.startsWith('Arduino');
Это точно нужно класть в платформу (например, как стиль команд) и пробрасывать из неё. 
Скорее всего, это долго, и нужно оставить над 76 и 80 строками TODO на этот счёт.

В том числе потому что в некоторых платформах пустые скобки не используют...

2024-06-07 09:00 UTC, bryzZz requested changes

2024-06-10 08:25 UTC, bryzZz approved these changes

2024-06-10 08:39 UTC, chekoopa approved these changes

2024-06-10 08:40 UTC, merged