Доработка копирования
kruzhok-team/lapki-client pull request #327
Opened 2024-06-06 14:41 UTC by bryzZz

Что сделано:
- Копирование из буфера обмена перенесено в поле контроллера, использовать буфер обмена не имеет смысла так как копирование происходит только внутри холста
- Добавлено смещении при вставке
- Добавлена комбинация CTRL + D

2024-06-07 06:37 UTC, chekoopa requested changes
Про отказ от буфера обмена я сильно сомневаюсь, потому что операции копирования сильно изолируются внутри одного редактора.

2024-06-07 06:37 UTC, chekoopa commented on src/renderer/src/lib/basic/EditorView.ts
> +    this.app.keyboard.on('ctrld', this.app.controller.copyAndPaseSelected);
`duplicateSelected`

2024-06-07 09:12 UTC, bryzZz commented
> Про отказ от буфера обмена я сомневаюсь, потому что операции копирования сильно изолируются внутри одного редактора.

Даже если будет куча редакторов, они все равно будут в одном приложении и будет удобно сделать через контроллеры

2024-06-11 09:30 UTC, chekoopa approved these changes
Список возможных проблем в будущем:
- Создаёт «параллельный» буфер обмена внутри приложения. То есть текст трогаться не будет. Это терпимо.
- Между приложений копировать не получится. Как бы, ну и ладно, нечего платформы перемешивать.
- Дублирование инвалидирует «внутренний» буфер обмена. Надо будет учесть.
- Копирование/вставка/дублирование не работает с вершинами. Как минимум в отсутствии дублирования может быть болевая точка.

2024-06-11 09:31 UTC, merged