Serial monitor
kruzhok-team/lapki-client pull request #328
Opened 2024-06-07 03:55 UTC by XidFanSan

Находится в разработке!

2024-07-03 04:56 UTC, chekoopa commented on src/main/settings.ts
> +    host: 'lapki-doc.polyus-nt.ru',
Это правка для единообразия? Кажется лишней (в том числе потому что у нас реально HTTP).

2024-07-03 04:58 UTC, XidFanSan commented on src/main/settings.ts
> +    host: 'lapki-doc.polyus-nt.ru',
Да, только для этого.

2024-07-04 01:36 UTC, chekoopa requested changes

2024-07-04 01:36 UTC, chekoopa commented on src/renderer/src/components/SerialMonitor.tsx
> +  const [baudRate, setBaudRate] = useState<SelectOption | null>({ label: '9600', value: '9600' });
Убирай избыточность.

```ts
const makeOption = () => {label: x, value: x};
...
const baudRateAll = [
  '9600', '19200', '38400', '57600', '115200', 
].map(makeOption);
```

Ну, и частот [гораздо больше](https://superuser.com/questions/488449/is-there-any-way-to-check-which-baud-rates-are-supported-on-a-serial-device). В наших проектах и 3 Мбод есть.

2024-07-04 01:36 UTC, chekoopa commented on src/renderer/src/components/Modules/SerialMonitor.ts
> +        const data = JSON.parse(message.data as string); // Парсим JSON
Ой небезопасно. Если устройство пришлёт что-то похожее на JSON, интерфейс сломается. Нужно либо явно слать строку, либо размечать отправляемые пакеты.

2024-07-04 01:36 UTC, chekoopa commented on src/renderer/src/components/SerialMonitor.tsx
> +      messageContainerRef.current.scrollTop = messageContainerRef.current.scrollHeight;
На заметку: https://stackoverflow.com/questions/37620694/how-to-scroll-to-bottom-in-react

Этот вариант в принципе норм (если работает).

2024-07-05 03:32 UTC, XidFanSan commented on src/renderer/src/components/Modules/SerialMonitor.ts
> +        const data = JSON.parse(message.data as string); // Парсим JSON
Я на сервере явно формирую строку, сделал это, чтобы клиент сразу получал чистые данные, которые необходимы, а не пытался их здесь формировать и т.д.

2024-07-05 03:34 UTC, XidFanSan commented on src/renderer/src/components/SerialMonitor.tsx
> +      messageContainerRef.current.scrollTop = messageContainerRef.current.scrollHeight;
Работает и довольно хорошо. Но если требуется переделать именно как по ссылке, то сделаю, непроблема.

2024-07-05 03:36 UTC, XidFanSan commented on src/renderer/src/components/SerialMonitor.tsx
> +  const [baudRate, setBaudRate] = useState<SelectOption | null>({ label: '9600', value: '9600' });
Я с Ваней искал информацию о скоростях, писалось лишь, что скорость у плат может быть разная. поэтому если и делать, то лучше через библиотечку, но увы и ах поиски не увенчались успехом, видимо придется лично в отдельном файле создавать данные со всеми возможными скоростями.

2024-07-05 03:41 UTC, XidFanSan commented on src/renderer/src/components/MainContainer/Tabs/Tabs.tsx
> +            <SerialMonitorTab />
Можешь пожалуйста написать пример технической заглушки.

2024-07-14 14:07 UTC, chekoopa approved these changes

2024-07-14 14:10 UTC, merged