Валидация имени компонента
kruzhok-team/lapki-client pull request #340
Opened 2024-06-17 09:45 UTC by Roundabout1

Проверка на соответствие имени стандарту языка C. Блокирует отправку формы и выводит ошибку под полем, если имя является неправильным.

Проверяет на то, чтобы имя не было пустым, чтобы оно состояло только из цифр, латинских букв и подчёркиваний ('_'), а также, чтобы на первой позиции не стояла цифра и имя целиком не соответствовало ключевому слову языка C.

![image](https://github.com/kruzhok-team/lapki-client/assets/86153878/d1b6b0f5-407d-4579-87da-a16ae6fd04d9)

2024-07-05 04:57 UTC, Roundabout1 commented
Сворачиваю PR обратно в драфт, потому что можно дополнить условия проверки: https://github.com/kruzhok-team/lapki-client/issues/237

2024-07-09 09:02 UTC, L140-beep commented
Классы фреймворка:
QEvt
QState
QSignal
QStateHandler
QHsm
Функции фреймфорка:
QMsm_simple_dispatch
QMsm_dispatch
do_transition
QHsm_top
QMsm_init
QHsm_ctor
Макросы:
Q_MAX_DEPTH
QEP_EMPTY_SIG_ 
Q_ENTRY_SIG
Q_EXIT_SIG
Q_INIT_SIG
Q_VERTEX_SIG
Q_USER_SIG
Q_RET_SUPER
Q_RET_UNHANDLED
Q_RET_HANDLED
Q_RET_IGNORED
Q_RET_TRAN
Q_MSM_UPCAST
Q_STATE_CAST
Q_UNHANDLED
Q_HANDLED
Q_TRAN
Q_SUPER
QMSM_INIT
QMSM_DISPATCH
SIMPLE_DISPATCH
SIGNAL_DISPATCH
PASS_EVENT_TO

2024-07-10 06:52 UTC, chekoopa requested changes

2024-07-10 06:52 UTC, chekoopa commented on src/renderer/src/components/ComponentFormFields.tsx
> +    if (name == '') {
Вся эта валидация будет проводиться **на каждом** нажатии клавиши. Мы точно этого хотим? Может быть, перенести её в submit?

2024-07-10 06:52 UTC, chekoopa commented on src/renderer/src/utils/index.ts
> +// список слов, используемых фреймворком компилятором
`используемых фреймворком QHSM в компиляторе`

2024-08-08 06:59 UTC, Roundabout1 commented on src/renderer/src/components/ComponentFormFields.tsx
> +    if (name == '') {
Зато пользователь сразу получает ответ, если он ввёл что-то некорректно. Название максимум занимает 20 символов, так что вряд ли такая проверка как-то существенно повлияет на производительность.

2024-08-13 05:01 UTC, chekoopa commented on src/renderer/src/components/ComponentEditModal.tsx
> +  const isNameDuplicated = useMemo(
Эту проверку можно перенести в функцию валидации.

2024-08-13 05:03 UTC, chekoopa commented on src/renderer/src/components/ComponentEditModal.tsx
> +    const firstSymbolRegex = '[A-Z]|[a-z]|_';
Имеет смысл пояснить, что в целом мы принимаем на вход только латинские буквы, цифры и подчёркивания.

2024-08-13 05:04 UTC, chekoopa requested changes
Почти-почти.

2024-08-13 06:04 UTC, chekoopa approved these changes

2024-08-13 06:05 UTC, merged