Реализация фокуса на редактор при нажатии пункта в контекстном меню и при закрытии модальных окон в компонентах.
kruzhok-team/lapki-client pull request #345
Opened 2024-06-19 04:40 UTC by XidFanSan

2024-06-19 05:34 UTC, bryzZz requested changes

2024-06-19 05:34 UTC, bryzZz commented on src/renderer/src/components/ComponentAddModal.tsx
> +  editor: CanvasEditor;
editor все компоненты достают через контекст

2024-06-19 05:34 UTC, bryzZz commented on src/renderer/src/components/ComponentEditModal.tsx
> +    editor.mouse.element.focus();
Сделай внутри CanvasEditor иетод focus и вызывай его. И не через мышку а через Canvas

2024-06-19 05:40 UTC, XidFanSan commented on src/renderer/src/components/ComponentAddModal.tsx
> +  editor: CanvasEditor;
const { model } = useEditorContext();
Он здесь уже достает model и вытащить editor не дает.

2024-06-19 05:40 UTC, XidFanSan commented on src/renderer/src/components/ComponentAddModal.tsx
> +  editor: CanvasEditor;
const model: EditorModel

2024-06-19 05:41 UTC, bryzZz commented on src/renderer/src/components/ComponentAddModal.tsx
> +  editor: CanvasEditor;
const editor = useEditorContext();
const { model } = editor;

2024-06-19 05:42 UTC, XidFanSan commented on src/renderer/src/components/ComponentAddModal.tsx
> +  editor: CanvasEditor;
const editor = useEditorContext();
  const components = editor.model.useData('elements.components');
Могу лишь так сделать

2024-06-19 05:53 UTC, bryzZz commented on src/renderer/src/components/ComponentAddModal.tsx
> +  editor: CanvasEditor;
editor пропсами никуда не нужно передавать. Все компоненты достают его через контекст. И все эти модлки пусть достанут его через контекст

2024-06-19 05:56 UTC, XidFanSan commented on src/renderer/src/components/ComponentAddModal.tsx
> +  editor: CanvasEditor;
Исправил, можешь смотреть.

2024-06-19 06:02 UTC, bryzZz requested changes

2024-06-19 06:02 UTC, bryzZz commented on src/renderer/src/lib/CanvasEditor.ts
> +    if (!this._canvas) {
То есть если компонента холста не существует (его теперь можно закрыть) то после редактирования компонента, каждый раз будет вылетать ошибка?

2024-06-19 06:02 UTC, bryzZz commented on src/renderer/src/hooks/useDiagramContextMenu.ts
> +            editor.focus();
Эти все фокусы нужно перенести в DiagramContextMenu, чтобы только один раз это делать

2024-06-19 06:08 UTC, XidFanSan commented on src/renderer/src/lib/CanvasEditor.ts
> +    if (!this._canvas) {
Так он же на наличие холста проверяет, а не на компонент

2024-06-19 06:09 UTC, XidFanSan commented on src/renderer/src/lib/CanvasEditor.ts
> +    if (!this._canvas) {
Вдруг холст является null

2024-06-19 07:10 UTC, bryzZz requested changes

2024-06-19 07:10 UTC, bryzZz commented on src/renderer/src/lib/CanvasEditor.ts
> +    if (!this._canvas) {
Открой схему, закрой вкладку холста, измени компонент, поймай поломку всей IDE)

2024-06-20 05:53 UTC, bryzZz commented on src/renderer/src/components/ComponentAddModal.tsx
> +  // Сброс к начальному состоянию после закрытия
Этот комментарий явно лжет)

2024-06-20 05:53 UTC, bryzZz commented on src/renderer/src/components/ComponentDeleteModal.tsx
> +  // Сброс к начальному состоянию после закрытия
Этот комментарий явно лжет)

2024-06-20 05:53 UTC, bryzZz commented on src/renderer/src/components/DiagramContextMenu.tsx
> +              isFolder || editor.focus(), onClose();
первый раз такое вижу, не понимаю вообще как это работает (функции через запятую). Перепиши через if для понятности пожалуйста

2024-06-20 05:57 UTC, XidFanSan commented on src/renderer/src/components/DiagramContextMenu.tsx
> +              isFolder || editor.focus(), onClose();
У меня и не такое заработает)))
Лады, щас исправлю)

2024-06-20 06:03 UTC, XidFanSan commented on src/renderer/src/components/DiagramContextMenu.tsx
> +              isFolder || editor.focus(), onClose();
Я вынес это в отдельную функцию.

2024-06-20 12:23 UTC, bryzZz approved these changes

2024-06-22 10:22 UTC, merged