Мультидокумент
kruzhok-team/lapki-client pull request #423
Opened 2024-08-21 10:41 UTC by L140-beep

## Что сделано?
- Полный рефакторинг работы с данными, теперь разные сущности отвечают за работу с моделью данных и за работу с их отображением на канвасе
- Возможность редактирования нескольких машин состояний одновременно
- Количество редакторов теперь не ограничено
- Теперь к каждому канвасу прикрепляется CanvasController, отвечающий за данные для отрисовки
- Появился класс ModelController, который посредством сигналов передает события об изменениях в данных в CanvasController, который на эти данные подписаны
- Появился схемотехнический экран, содержащий информацию обо всех компонентах каждой МС
## Трекер задач
- [x] CanvasController
  - [x] Создание
  - [x] Удаление
  - [x] Изменение
- [x] Исправление ModelController
- [x] Избавиться от CanvasScheme, useCanvasContext и т.д.
- [x] Несколько машин состояний
- [x] Назначить начальным
- [x] Дублирование
- [x] Вставка
- [x] Ивенты состояний
- [x] Копирование
- [x] Переходы
- [x] Заметки 
- [x] Redu неправильно линкует состояние (для проверки - создание состояния - пеместить в родителя)
- [x] Открытие/сохранение схемы
- [x] Неправильные координаты вложенных состояний
- [x] Баг с вылетом при создании новой схемы, когда уже открыта схема
- [x] Открытие схемы из шаблона
- [x] Баг с вылетом при удалении вложенных состояний
- [x] При переключении вкладок теряются созданные компоненты
- [x] Вылет, если сначала создать пустую схему, а затем открыть существующую
- [x] Создание и открытие машин состояний через UI
- [x] Схемотехнический экран
- [x] При линковке состояния открывается модалка с его редактированием
- [x] Канвас зависает, если удалить состояние и в него есть переход
- [x] Вылет приложения, если удалить состояние из темплейта
- [x] Нельзя "вытащить" дочернее состояние (Нельзя и в мейн ветке)
- [x] При автоматическом измении перехода из начального состояния открывается модалка
- [x] Нельзя полностью удалить состояние со вложенностью
- [x] Если состояние со вложенностью остается последним, то у детей не появляется начального состояния
- [x] Сломалось переключение вкладок не между канвасами
- [x] Если закрыть вкладку и начать редактировать МС, то приложение вылетает

UI:
- [x] Отображение списка машин состояний
- [x] Добавление машин состояний
- [x] Удаление машин состояний
- [x] Отображение списка платформ выпадающим списком
- [x] Открытие редактора машин состояний через контекстное меню
- [x] При выделении компонента на схемотехническом экране выделяется другой компонент

AFTER MERGE:
- [x] Хранение visual в CanvasController
- [x] функции для изменения формата заметок в ModelController
- [x] emit изменений формата заметок
- [x] изменение visual в CanvasController
- [x] useData('elements.visual')
- [x] Очень плохо пробрасываются данные в модалку текстового режима
- [x] Создается лишняя машина ссостояний, если сначала создать машину состояний, а потом открыть схемотехнический экран
- [x] Не создается псевдосостояние выбора, вылетает все
- [x] При нажатии подтвердить не закрывается модалка с созданием машины состояний и не открывается вкладка с машиной состояний
- [x] Не создается GhostTransition из состояний из шаблона, при создании новых все работает
- [x] Вылетает если несколько раз создать схему (опять вкладки)
- [x] Приложение зависисает намертво, если создать конечное состояние внутри состояния
- [x] При удалении вложенного состояния умирает иерархия
- [x] При удалении через 'Delete' переходы и заметки удаляются только во вьюшке, но не в модели (прокинуть везде сигнал select*ElementName*)
- [x] Значки компонентов не ререндерятся, хотя платформа подгрузилась
- [x] После переименования МС в списке компонентов остается старое название (не вызывается ререндер)
- [x] ИСТОРИЯ
- [x] Вылет при попытке закрыть вкладку с кодом
- [x] Не выделяются заметки
- [x] Не компилируются несколько МС
- [x] Не создаются псевдосостояния выбора внутри других состояний
- [x] unlink псевдосостояния
- [x] В данных не меняется позиция компонентов
- [x] Сохранять позицию МС в схеме
- [x] Не обновляется название МС на схемотехническом экране

2024-10-16 14:27 UTC, bryzZz commented on src/renderer/src/hooks/useStateMachines.ts
> +      name: sm.name ? sm.name : smId,
sm.name ?? smId,

2024-10-16 14:27 UTC, bryzZz commented on src/renderer/src/hooks/useStateMachines.ts
> +    if (data.name != smName) {
!===================

2024-10-16 14:27 UTC, bryzZz commented on src/renderer/src/hooks/useStateMachines.ts
> +      renameTab(smName ? smName : idx, data.name ? data.name : idx);
использщуй ??

2024-10-16 14:27 UTC, bryzZz commented on src/renderer/src/hooks/useStateMachines.ts
> +    const machines = [...Object.entries(modelController.model.data.elements.stateMachines)];
Object.entries итак массив возвращает

2024-10-16 14:27 UTC, bryzZz commented on src/renderer/src/lib/basic/EditorView.ts
> +  constructor(public app: CanvasEditor, modelController: ModelController) {
Раз уж public app: CanvasEditor то надо и public modelController: ModelController

2024-10-16 14:27 UTC, bryzZz commented on src/renderer/src/lib/basic/EditorView.ts
> +  get children() {
А зачем?

2024-10-16 14:27 UTC, bryzZz commented on src/renderer/src/lib/data/EditorModel/EditorModel.ts
> +      events = args.events || [],
че

2024-10-16 14:27 UTC, bryzZz commented on src/renderer/src/lib/data/EditorModel/EditorModel.ts
> -  /**
Заработал на текстовые?

2024-10-16 14:27 UTC, bryzZz commented on src/renderer/src/lib/data/History.ts
> +    // >>>>>>> main
Что-то протекло

2024-10-16 14:27 UTC, bryzZz commented on src/renderer/src/store/useSidebar.ts
> +  menu,
Принято с большой буквы Menu

2024-10-16 14:27 UTC, bryzZz commented on src/renderer/src/lib/drawable/TransitionNode/Transition.ts
> +  constructor(protected app: CanvasEditor, public id: string, smId: string, data: DataTransition) {
все через public

2024-10-16 14:27 UTC, bryzZz commented on src/renderer/src/lib/drawable/StateMachineNode/StateMachine.ts
> +  __position: Point;
Зачем это нужно? Почему нельзя просто модификатор доступа?

2024-10-16 14:27 UTC, bryzZz commented on src/renderer/src/lib/drawable/Picto.tsx
> +      const { x, y, width, height } = bounds;
Что произошло с отступами?

2024-10-16 14:27 UTC, bryzZz commented on src/renderer/src/lib/drawable/ComponentNode/Component.ts
> +  __position: Point;
Писал в другом комменте

2024-10-18 05:49 UTC, L140-beep commented on src/renderer/src/components/MainContainer/Tabs/Tabs.tsx
> +        // TODO: ДОДЕЛАТЬ
Я уже и сам не помню, удалил

2024-10-18 05:50 UTC, L140-beep commented on src/renderer/src/components/MainContainer/Tabs/Tabs.tsx
> +            showName={true}
На будущее, если будет вкладка без имени

2024-10-18 05:51 UTC, L140-beep commented on src/renderer/src/components/NodeModal/ActionsModal/ActionsModal.tsx
> +  // TODO: Прокинуть сюда машину состояний
Пока что так, да. Это вызовет проблемы, когда будет общий канвас со всеми машинами состояний, которые можно редактировать. Но так как общего канваса нет, то и проблем тоже

2024-10-18 05:53 UTC, L140-beep commented on src/renderer/src/components/NoteEdit.tsx
> +    // TODO (L140-beep): А работает ли?
Я его написал, когда Lapki даже близко не запускались, сейчас-то понятно что все работает, удалил

2024-10-18 05:54 UTC, L140-beep commented on src/renderer/src/components/PropertiesModal/PropertiesModal.tsx
> +      Object.entries(meta).map(([name, value]) => ({ name, value })) as never // Почему линтер ругается?
Оставил, но мы-то знаем, что все равно не пофиксится

2024-10-18 05:57 UTC, L140-beep commented on src/renderer/src/components/Sidebar/StateMachinesTab/StateMachineTab.tsx
> +// import React, { useReducer, useRef, RefObject } from 'react';
Комментировать - не мешки ворочать

2024-10-18 06:04 UTC, L140-beep commented on src/renderer/src/components/TextModeModal.tsx
> +  // TODO: Исправить
Да я уже забыл что за проблема была, значит ее уже нет

2024-10-18 06:05 UTC, L140-beep commented on src/renderer/src/components/UI/Badge.tsx
> +
Ругается, если их нет, тут разные группы импортов почему-то. Хотя что одно внешняя библиотека, что другое

2024-10-18 06:15 UTC, L140-beep commented on src/renderer/src/lib/basic/EditorView.ts
> +  get children() {
Исправил, беру из this.app.controller.model

2024-10-18 06:15 UTC, L140-beep commented on src/renderer/src/lib/data/EditorModel/EditorModel.ts
> +      events = args.events || [],
Бес попутал

2024-10-18 06:17 UTC, L140-beep commented on src/renderer/src/components/UI/Tabs/Tabs.tsx
> +          }}
Дебаггер туда вставлял, вкладки очень больная тема у нас

2024-10-18 06:18 UTC, L140-beep commented on src/renderer/src/lib/basic/EditorView.ts
> +  constructor(public app: CanvasEditor, modelController: ModelController) {
Да все, нет больше никакого ModelController

2024-10-18 06:19 UTC, L140-beep commented on src/renderer/src/lib/data/History.ts
> +    // >>>>>>> main
Утекло обратно

2024-10-18 06:25 UTC, L140-beep commented on src/renderer/src/lib/drawable/StateMachineNode/StateMachine.ts
> +  __position: Point;
я питонист

2024-10-18 06:26 UTC, L140-beep commented on src/renderer/src/lib/drawable/Picto.tsx
> +      const { x, y, width, height } = bounds;
Фиг знает, Prettier так сделал

2024-11-15 07:58 UTC, chekoopa commented on src/renderer/src/store/EditorContext.ts
> +// import { createContext, useContext } from 'react';
Уже не используется? Может, снести файл?

2024-11-15 08:27 UTC, chekoopa commented on src/renderer/src/store/useTabs.ts
> +      // TODO: Менять текущий главный канвас при закрытии вкладки
Любые TODO лучше снабжать своим ником, чтобы было, у кого уточнить смысл.

2024-11-15 08:44 UTC, chekoopa commented on src/renderer/src/components/ComponentAddModal.tsx
> +  // TODO: Прокинуть сюда машину состояний
???

2024-11-15 09:09 UTC, chekoopa commented on src/renderer/src/components/ComponentAddModal.tsx
> +  const editor = modelController.getCurrentCanvas();
`// TODO(L140-beep): рефакторинг, убрать editor и сделать доступ через modelController`

2024-11-15 09:42 UTC, chekoopa commented on src/renderer/src/components/ComponentEditModal.tsx
> +  const editor = modelController.getCurrentCanvas();
`// TODO(L140-beep): рефакторинг, убрать editor и сделать доступ через modelController`

`const editor = modelController.controllers[headControllerId].app;`

2024-11-15 09:44 UTC, chekoopa commented on src/renderer/src/components/ComponentAddModal.tsx
> +  // TODO: Прокинуть сюда машину состояний
`// TODO(L140-beep): здесь нужно будет прокинуть машину состояний, когда появится общий канвас`

2024-11-15 09:45 UTC, chekoopa commented on src/renderer/src/components/DiagramContextMenu/DiagramContextMenu.tsx
> +  // TODO: Передавать в модалки машину состояний
`// TODO(L140-beep): здесь нужно будет прокинуть машину состояний, когда появится общий канвас`

2024-11-15 09:46 UTC, chekoopa commented on src/renderer/src/components/DiagramContextMenu/DiagramContextMenu.tsx
> +                dimensions: { width: 450, height: 100 }, // TODO (L140-beep): уточнить
Как будто напрашивается вынести все эти размеры во внешние константы.

2024-11-15 09:47 UTC, chekoopa commented on src/renderer/src/components/DiagramContextMenu/DiagramContextMenu.tsx
> +                dimensions: { width: 450, height: 100 },
Зачем ему размеры?

2024-11-15 09:47 UTC, chekoopa commented on src/renderer/src/components/DiagramContextMenu/DiagramContextMenu.tsx
> +                dimensions: { width: 450, height: 100 },
Зачем ему размеры?

2024-11-15 09:48 UTC, chekoopa commented on src/renderer/src/components/DiagramContextMenu/Menus/NoteMenu.tsx
> +  const editor = modelController.getCurrentCanvas();
`// TODO(L140-beep): рефакторинг, убрать editor и сделать доступ через modelController`

`const editor = modelController.controllers[headControllerId].app;`

2024-11-15 09:51 UTC, chekoopa commented on src/renderer/src/components/MainContainer/Tabs/Tabs.tsx
> +            draggable={tab.type !== 'editor'}
Пока что всегда должен быть `true`. Редактор у нас больше не закреплён.

2024-11-15 10:00 UTC, chekoopa commented on src/renderer/src/lib/drawable/Shape.ts
>        const children = [
Для протокола: это очень нехорошая точка, которая с виду и замедляет отрисовку, и баги легко вызывает. Требует внимания.

2024-11-15 10:05 UTC, chekoopa commented on src/renderer/src/components/Documentation/Documentation.tsx
> +  const editor = modelController.getCurrentCanvas();
`// TODO(L140-beep): рефакторинг, убрать editor и сделать доступ через modelController`

`const editor = modelController.controllers[headControllerId].app;`

2024-11-15 10:07 UTC, chekoopa commented on src/renderer/src/components/EditorSettings.tsx
> +    canvas.view.changeScale(0.1);
Уф, двоится

2024-11-15 10:11 UTC, chekoopa commented on src/renderer/src/components/NoteEdit.tsx
> +  const stateMachines = Object.keys(modelController.controllers[headControllerId].stateMachinesSub);
Нужно ли добавить сюда?

`// TODO(L140-beep): здесь нужно будет прокинуть машину состояний, когда появится общий канвас`

2024-11-15 10:13 UTC, chekoopa commented on src/renderer/src/components/Sidebar/Explorer/Explorer.tsx
> +  const editor = modelController.getCurrentCanvas();
Устал писать на каждый `getCurrentCanvas`, поэтому это будет последний комментарий про него. Со слов, есть запрос на удаление этой функции, но надо будет это понять в следующих итерациях.

2024-11-15 10:20 UTC, chekoopa commented on src/renderer/src/components/StateNameEdit.tsx
> +    // TODO (L140-beep): работает ли?
И как, работает?

2024-11-15 10:25 UTC, chekoopa commented on src/renderer/src/lib/data/EditorModel/Serializer.ts
> +    const state = this.data.elements.stateMachines[smId].states[id];
Должен ли после каждого `stateMachines[smId]` быть `?` в качестве защиты от дурака? Типа, обращение к несуществующей МС.

2024-11-15 10:28 UTC, chekoopa commented on src/renderer/src/lib/drawable/Events.ts
> +    // TODO: Откуда брать components по-нормальному?
`// TODO(L140-beep): ...`

2024-11-15 10:35 UTC, chekoopa commented on src/renderer/src/components/StateMachineFormFields.tsx
> +export const StateMachineFormFields: React.FC<StateMachineFormFields> = ({
Описать назначение класса

2024-11-15 10:36 UTC, chekoopa commented on src/renderer/src/components/StateMachineFormFields.tsx
> +            hint={'Название машины состояний.' + 'string'}
Странное соединение строк. Нужен ли здесь `\n`?

2024-11-15 10:38 UTC, chekoopa commented on src/renderer/src/components/PropertiesModal/PropertiesModal.tsx
> +  // TODO: Передавать в модалки машину состояний
`// TODO(L140-beep): здесь нужно будет прокинуть машину состояний, когда появится общий канвас`

2024-11-15 10:38 UTC, chekoopa commented on src/renderer/src/components/PropertiesModal/PropertiesModal.tsx
> +      Object.entries(meta).map(([name, value]) => ({ name, value })) as never // TODO: Почему линтер ругается?
`// TODO(L140-beep): ...`

2024-11-15 10:40 UTC, chekoopa commented on src/renderer/src/components/PropertiesModal/PropertiesModal.tsx
> +      const stat = await window.api.fileHandlers.getMetadata(basename);
На будущее: кажется тонким местом, где может быть подвисание/вылет.

2024-11-15 10:40 UTC, chekoopa commented on src/renderer/src/components/Sidebar/Explorer/Component.tsx
> +  onCallContextMenu: () => void; // TODO: Сделать контекстное меню для машин состояний
`// TODO(L140-beep): ...`

2024-11-15 10:45 UTC, chekoopa commented on src/renderer/src/components/NodeModal/hooks/useActions.ts
> +  // TODO: решить проблему с машинами состояний
Какую проблему?

2024-11-15 10:46 UTC, chekoopa commented on src/renderer/src/components/NodeModal/hooks/useCondition.tsx
> +  // TODO: Передавать в модалки машину состояний
`// TODO(L140-beep): здесь нужно будет прокинуть машину состояний, когда появится общий канвас`

2024-11-15 10:51 UTC, chekoopa commented on src/renderer/src/hooks/useComponents.ts
> +  // TODO: Передавать в модалки машину состояний
`// TODO(L140-beep): здесь нужно будет прокинуть машину состояний, когда появится общий канвас`

2024-11-15 10:54 UTC, chekoopa commented on src/renderer/src/hooks/useFileOperations.ts
> +    for (const controllerId in modelController.controllers) {
ОБСУДИТЬ! Кажется, разумнее сейчас оставить открытие только первой машины состояний.

И в будущем сделать открытие всех машин опцией. Но это в будущем.

2024-11-15 11:01 UTC, chekoopa commented on src/renderer/src/lib/data/EditorModel/FilesManager.ts
> +      console.log(openData);
Остался отладочный трейс

2024-11-15 12:13 UTC, chekoopa commented on src/renderer/src/components/DiagramEditor.tsx
> +  const smId = stateMachines[0]; // TODO: Как понять в какую именно машину состояний мы добавляем?
`// TODO(L140-beep): здесь нужно будет прокинуть машину состояний, когда появится общий канвас`

2024-11-15 12:15 UTC, chekoopa commented on src/renderer/src/components/DiagramEditor.tsx
> +  // TODO: Прокинуть smId в другие модалки
`// TODO(L140-beep): ...`

2024-11-15 12:17 UTC, chekoopa commented on src/renderer/src/components/Hierarchy/Hierarchy.tsx
> +  // TODO: Пофиксить иерархию, чтобы на ней отображались разные МС
// TODO(L140-beep): реализовать отображение нескольких МС, когда появится общий канвас

2024-11-15 12:18 UTC, chekoopa commented on src/renderer/src/components/Hierarchy/Hierarchy.tsx
> +    controller.selectState({ smId, id: item.index.toString() });
Такое впечатление, что здесь не хватает псевдосостояний.

2024-11-15 12:21 UTC, chekoopa commented on src/renderer/src/components/NodeModal/StateModal.tsx
> - */
Очень зря убрал.

2024-11-15 12:24 UTC, chekoopa commented on src/renderer/src/components/NodeModal/hooks/useTrigger.tsx
> +  // TODO: Передавать в модалки машину состояний
`// TODO(L140-beep): здесь нужно будет прокинуть машину состояний, когда появится общий канвас`

2024-11-15 12:25 UTC, chekoopa commented on src/renderer/src/components/Sidebar/Explorer/ComponentsList.tsx
> +  // TODO: Передавать в модалки машину состояний
// TODO(L140-beep): здесь нужно будет прокинуть машину состояний, когда появится общий канвас

2024-11-15 12:26 UTC, chekoopa commented on src/renderer/src/components/Sidebar/Menu.tsx
> +      text: 'Открыть экран',
`Открыть схемоэкран`

2024-11-15 12:26 UTC, chekoopa commented on src/renderer/src/components/Sidebar/Menu.tsx
> +  // TODO: visual
???

2024-11-15 12:33 UTC, chekoopa commented on src/renderer/src/components/Sidebar/StateMachinesTab/StateMachineDeleteModal.tsx
> +      </p>
Интересный остаточек. Если удаление нельзя отменить, об этом надо будет указать. Иначе, текст можно убрать.

2024-11-15 12:35 UTC, chekoopa commented on src/renderer/src/lib/data/GraphmlBuilder.ts
> -      unsupportedDataNodes: getNoteFormatNode(note),
Куда делось форматирование заметок? Надо вернуть...

2024-11-15 12:36 UTC, chekoopa commented on src/renderer/src/lib/drawable/ComponentNode/Component.ts
> +    // TODO: Переделать платформу
Что именно переделать?

2024-11-15 12:40 UTC, chekoopa commented on src/renderer/src/lib/drawable/StateMachineNode/StateMachine.ts
> +    // if (this.isSelected) {
`// TODO(L140-beep): вернуть выделение`

Или в целом его вернуть...

2024-11-15 12:41 UTC, chekoopa commented on src/renderer/src/lib/data/Initializer.ts
> +    this.app.view.viewCentering();
Зачем оно двоится?

2024-11-15 12:42 UTC, chekoopa commented on src/renderer/src/lib/data/Initializer.ts
> +    // TODO: Вот эта штука почему-то вызывается при смене вкладок
Этот TODO актуален? Равно как закомментированные ниже строки.

2024-11-15 12:43 UTC, chekoopa commented on src/renderer/src/lib/data/Initializer.ts
> +      // this.createComponentView(sm, name);
Это нужный код?

2024-11-15 12:45 UTC, chekoopa commented on src/renderer/src/hooks/useStateMachines.ts
> +    // TODO: вызывает краш IDE
Актуально?!

2024-11-15 12:47 UTC, chekoopa commented on src/renderer/src/lib/data/GraphmlParser.ts
> +      }, // TODO (L140-beep): что-то нужно с этим придумать
Чуть подробнее, что именно придумать?

2024-11-15 12:48 UTC, chekoopa commented on src/renderer/src/lib/data/GraphmlParser.ts
> -function getNotes(rawNotes: {[id: string]: CGMLNote}) {
Куда делось форматирование? Надо вернуть...

2024-11-15 12:49 UTC, chekoopa commented on src/renderer/src/lib/data/GraphmlParser.ts
> +      sm.notes = rawSm.notes;
Куда пропало форматирование? Надо вернуть...
(Здесь должен быть вызов getNotes, который случайно вырезан при слиянии.)

2024-11-15 12:51 UTC, chekoopa commented on src/renderer/src/components/Sidebar/Explorer/StateMachineComponentList.tsx
> +      {/* <Panel
Почему это вынуто из панели?

2024-11-15 13:33 UTC, chekoopa commented on src/renderer/src/lib/data/ModelController/NotesController.ts
> -    if (canUndo) {
Куда делся откат действия?

2024-11-17 13:06 UTC, L140-beep commented on src/renderer/src/components/DiagramContextMenu/DiagramContextMenu.tsx
> +                dimensions: { width: 450, height: 100 },
Используется для вычисления размера родительского контейнера на стороне ModelController.

2024-11-17 13:06 UTC, L140-beep commented on src/renderer/src/components/DiagramContextMenu/DiagramContextMenu.tsx
> +                dimensions: { width: 450, height: 100 },
Используется для вычисления размера родительского контейнера на стороне ModelController.

2024-11-17 13:08 UTC, L140-beep commented on src/renderer/src/lib/drawable/Shape.ts
>        const children = [
Не совсем понимаю как это замедляет отрисовку, мы просто храним scale и в контроллере, и в модели

2024-11-17 13:24 UTC, L140-beep commented on src/renderer/src/components/EditorSettings.tsx
> +    canvas.view.changeScale(0.1);
Заменил на вот такую функцию в ModelController:
```
  changeScale(diff: number, replace = false) {
    this.model.setScale(replace ? diff : this.model.data.scale + diff);
    const controller = this.controllers[this.model.data.headControllerId];
    controller.view.changeScale(diff, replace);
    this.emit('changeScale', replace ? diff : this.model.data.scale + diff);
  }
```

2024-11-17 13:27 UTC, L140-beep commented on src/renderer/src/components/StateNameEdit.tsx
> +    // TODO (L140-beep): работает ли?
Работает

2024-11-17 13:29 UTC, L140-beep commented on src/renderer/src/components/StateMachineFormFields.tsx
> +export const StateMachineFormFields: React.FC<StateMachineFormFields> = ({
Э? Это же просто форма, зачем ей описание?

2024-11-17 13:34 UTC, L140-beep commented on src/renderer/src/components/NodeModal/hooks/useActions.ts
> +  // TODO: решить проблему с машинами состояний
// TODO(L140-beep): здесь нужно будет прокинуть машину состояний, когда появится общий канвас

2024-11-17 13:42 UTC, L140-beep commented on src/renderer/src/components/Hierarchy/Hierarchy.tsx
> +    controller.selectState({ smId, id: item.index.toString() });
Добавил:
```ts
modelController.selectChoiceState({ smId, id: item.index.toString() });
```
Для других ПС выделение не предусмотрено

2024-11-17 13:42 UTC, L140-beep commented on src/renderer/src/components/NodeModal/StateModal.tsx
> - */
Вернул

2024-11-17 13:43 UTC, L140-beep commented on src/renderer/src/components/Sidebar/Menu.tsx
> +  // TODO: visual
Старая тудушка, убрал

2024-11-17 13:45 UTC, L140-beep commented on src/renderer/src/components/Sidebar/StateMachinesTab/StateMachineDeleteModal.tsx
> +      </p>
```ts
      <p className="italic">Внимание! Удаление машины состояний нельзя отменить!</p>
```

2024-11-17 13:55 UTC, L140-beep commented on src/renderer/src/lib/data/GraphmlBuilder.ts
> -  ];
Вернул

2024-11-17 13:55 UTC, L140-beep commented on src/renderer/src/lib/drawable/ComponentNode/Component.ts
> +    // TODO: Переделать платформу
Не помню, удалил

2024-11-17 14:03 UTC, L140-beep commented on src/renderer/src/lib/drawable/StateMachineNode/StateMachine.ts
> +    // if (this.isSelected) {
Короче, там проблема в том, что вот эта маленькая МС - это тоже компонент, который существует в обход ComponentsController, и поэтому он не реагирует ни на что, это надо переделать

2024-11-17 14:07 UTC, L140-beep commented on src/renderer/src/lib/data/Initializer.ts
> +    // TODO: Вот эта штука почему-то вызывается при смене вкладок
Это уже не актуально, потому что инициализация компонентов идет через CanvasController И Initializer, и главным теперь является CanvasController. Это все закомментировано, потому что у нас init вызывается на каждый mount CanvasEditor, что приводило к дублированию

2024-11-17 14:10 UTC, L140-beep commented on src/renderer/src/lib/data/Initializer.ts
> +    this.app.view.viewCentering();
Удалил

2024-11-17 14:10 UTC, L140-beep commented on src/renderer/src/lib/data/Initializer.ts
> +      // this.createComponentView(sm, name);
Нет, создание вьюшек для компонентов идет в функции initStateMachines, здесь просто общая инициализация иконок в PlatformManager

2024-11-17 14:14 UTC, L140-beep commented on src/renderer/src/hooks/useStateMachines.ts
> +    // TODO: вызывает краш IDE
Блять... Это не мой комментарий, я не знал, что если попытаться удалить последнюю МС, то все крашится

2024-11-17 14:17 UTC, L140-beep commented on src/renderer/src/hooks/useStateMachines.ts
> +    // TODO: вызывает краш IDE
Я не заметил этот комментарий, когда мержил ПР -_-

2024-11-17 14:38 UTC, L140-beep commented on src/renderer/src/lib/data/ModelController/NotesController.ts
> -    if (canUndo) {
Потому что эти контроллеры больше не отвечают за историю в принципе

2024-11-17 14:46 UTC, L140-beep commented on src/renderer/src/hooks/useStateMachines.ts
> +    // TODO: вызывает краш IDE
Пофиксил

2024-11-17 14:51 UTC, L140-beep commented on src/renderer/src/components/Sidebar/Explorer/StateMachineComponentList.tsx
> +      {/* <Panel
Ну потому что у нас же есть список компонентов в другой вкладки, оттуда и вытянули все, забыли комменты удалить

2024-11-17 15:23 UTC, chekoopa commented on src/renderer/src/components/Modules/Compiler.ts
> +            ws.send(JSON.stringify(downgradeStateMachine(data as StateMachine)));
Возможно, весь прилежащий набор функций (`downgrade...`) стоило бы вынести в отдельный модуль.

2024-11-17 15:37 UTC, chekoopa commented on src/renderer/src/lib/data/ModelController/NotesController.ts
> -    if (canUndo) {
А почему ниже код закомментирован?

2024-11-17 15:39 UTC, chekoopa commented on src/renderer/src/lib/data/ModelController/NotesController.ts
>      this.view.children.remove(note, Layer.Notes);
При этом точно удалятся зависимые переходы?

2024-11-17 15:51 UTC, chekoopa commented on src/renderer/src/lib/data/GraphmlParser.ts
> +function getNotes(rawNotes: { [id: string]: CGMLNote }) {
Не понимаю, что мешало вернуть функцию на то же место, где она и была раньше. Ну пусть теперь уже здесь лежит, хотя дифф будет грязнее (а чем грязнее дифф, тем больше шансов конфликта слияния)

2024-11-17 15:54 UTC, L140-beep commented on src/renderer/src/lib/data/ModelController/NotesController.ts
>      this.view.children.remove(note, Layer.Notes);
Не удаляются и крашаться, сейчас буду фиксить

2024-11-17 16:01 UTC, L140-beep commented on src/renderer/src/lib/data/ModelController/NotesController.ts
>      this.view.children.remove(note, Layer.Notes);
Проблема была в другом, при выборке зависимых переходов, мы ориентировались на то, что targetId равен id заметки, а нужно было ориентироваться на sourceId

2024-11-17 16:04 UTC, L140-beep commented on src/renderer/src/lib/data/ModelController/NotesController.ts
> -    if (canUndo) {
Потому что я не перенес историю форматирования заметок, а просто пока закомментировал и в истории, и здесь, чтобы вернуться к этому позже

2024-11-17 16:13 UTC, L140-beep commented on src/renderer/src/components/Modules/Compiler.ts
> +            ws.send(JSON.stringify(downgradeStateMachine(data as StateMachine)));
Перенес `downgrade...`  в модуль `DowngradeResponse.ts`, а `actualize...` в `ActualizeResponse.ts`

2024-11-18 09:53 UTC, chekoopa commented on src/renderer/src/components/Sidebar/Menu.tsx
> -      className: 'border-t border-border-primary',
Стоит ли вернуть отбивку кнопки?

2024-11-18 10:00 UTC, chekoopa commented on src/renderer/src/components/StateMachineFormFields.tsx
> +export const StateMachineFormFields: React.FC<StateMachineFormFields> = ({
Затем, что документировать надо все классы, но пока что лишь этот сбил с толку так, чтобы появился этот комментарий.

2024-11-18 10:05 UTC, chekoopa commented on src/renderer/src/lib/data/ModelController/TransitionsController.ts
>      //TODO: (XidFanSan) где-то должна быть проверка, что цель может быть не-состоянием, только если источник – заметка.
Возможно, здесь прячется старый баг.

2024-11-18 10:08 UTC, chekoopa commented on src/renderer/src/lib/data/History.ts
> +  // TODO (L140-beep): удаление машин состояний
Сразу после мержа?

2024-11-18 10:08 UTC, chekoopa commented on src/renderer/src/lib/data/History.ts
> +  // }),
Почему закомментировано?

2024-11-18 10:09 UTC, chekoopa commented on src/renderer/src/lib/data/History.ts
> -  }),
Нужно вернуть форматирование...

2024-11-18 10:09 UTC, chekoopa commented on src/renderer/src/lib/data/History.ts
> +  // }),
Почему закомментировано?

2024-11-18 10:09 UTC, chekoopa commented on src/renderer/src/lib/data/History.ts
> +  // }),
Нужно вернуть...

2024-11-18 15:00 UTC, chekoopa commented on src/renderer/src/lib/data/ModelController/StatesController.ts
> +        smId: '',
Почему этот smId пустой, а следующий – нет?

2024-11-18 15:01 UTC, chekoopa commented on src/renderer/src/lib/data/ModelController/StatesController.ts
> +    this.controller.selectChoice({ smId: state.smId, id: state.id });
Лучше указать, почему здесь и выше так двоится.
Если это, конечно, штатное положение дел.

2024-11-18 16:18 UTC, chekoopa commented on src/renderer/src/lib/data/ModelController/ModelController.ts
> +  private getChildrenContainerHeight(smId: string, stateId: string) {
Казалось, это всё в Drawable висит, а тут дублируется так радикально... Имеет смысл оставить пояснение.

2024-11-18 16:21 UTC, chekoopa commented on src/renderer/src/lib/data/ModelController/ModelController.ts
> +    // if (canUndo) {
Надо добавить.

2024-11-18 16:22 UTC, chekoopa commented on src/renderer/src/lib/data/ModelController/ModelController.ts
> +    // TODO (L140-beep): History
Тоже, по каждой из трёх функций ниже. Либо не давать фичи вовсе, либо привести к рабочему состоянию. 

Компромисс – скрыть команды из контекстного меню, но я к нему не хочу прибегать.

2024-11-18 16:23 UTC, chekoopa requested changes
Учесть комментарии выше и запросить ревью заново.

2024-11-18 16:25 UTC, chekoopa commented on src/renderer/src/components/DiagramContextMenu/DiagramContextMenu.tsx
> +                dimensions: { width: 450, height: 100 },
Вот это пояснение и просится в код.

2024-11-18 16:26 UTC, chekoopa commented on src/renderer/src/lib/drawable/Shape.ts
>        const children = [
Ты не понял, я комментарий на генерацию `children` поставил.

2024-11-19 07:25 UTC, chekoopa approved these changes

2024-11-19 07:26 UTC, chekoopa commented
Ввиду отсутствия критических ошибок (кроме регрессий) решено делать слияние. Остальное делаем через issue.

2024-11-19 07:27 UTC, merged