Поддержка платформы МС-ТЮК
kruzhok-team/lapki-client pull request #428
Opened 2024-09-02 07:53 UTC by L140-beep

2024-09-03 05:52 UTC, chekoopa requested changes

2024-09-03 05:52 UTC, chekoopa commented on resources/platform/ms-tuc-1.json
`tjc-ms1-main`

2024-09-09 04:49 UTC, chekoopa approved these changes

2024-10-05 04:01 UTC, chekoopa requested changes
Конфликтует с текущей версией платформ.

2024-10-16 06:45 UTC, chekoopa commented on demos/CyberiadaSchemas/ms-tuc-blinker.graphml
> +name/ Arduino Blinker
Не то название схемы. И название файла тоже лучше поменять на `tjc-ms1-blinker.graphml`

2024-10-16 06:45 UTC, chekoopa commented on demos/CyberiadaSchemas/ms-tuc-blinker.graphml
> +pin/ 12
Здесь должен быть светодиод 1

2024-10-16 06:48 UTC, chekoopa commented on resources/platform/BearlogaDefend-1.0.json
> +  "description": "придумайте описание Берлоги",
Вернуть описание из старой платформы!

2024-10-16 06:49 UTC, chekoopa commented on resources/platform/BearlogaDefend-1.0.json
> +    "АнализаторЦели": {
Проверь синглтоны у всех компонентов Пасеки. АнализаторЦели добавляется не как синглтон.

2024-10-16 06:53 UTC, chekoopa commented on resources/platform/tjc-ms1-main.json
> +  "id": "tjc-ms1-main",
По идее, в названии файла тоже должна быть ревизия.

2024-10-16 09:59 UTC, L140-beep commented on resources/platform/tjc-ms1-main.json
> +  "id": "tjc-ms1-main",
Поставил tjc-ms1-main-a4, так как она у нас сейчас на руках

2024-10-16 10:25 UTC, chekoopa commented on resources/platform/BearlogaDefend-1.0.json
> +    "АнализаторЦели": {
Значит, намечается баг. Этот флаг у нас пока не работает в модалке редактирования компонента. У автобортника предлагает поменять имя анализатору цели.

2024-11-23 16:45 UTC, chekoopa commented on resources/platform/ArduinoMicro-1.0.json
> +          "type": [0, 1],
Не лучше ли через DEFINE-константы?

2024-11-23 16:45 UTC, chekoopa commented on resources/platform/ArduinoUno-1.0.json
> +          "type": ["BUTTON_PULLUP", "BUTTON_PULLDOWN"],
...Ну вот как здесь.

2024-11-23 16:59 UTC, chekoopa commented on resources/platform/tjc-ms1-mtrx-a1-1.0.json
> +        "setPixel": {
А у нас таки светодиоды ШИМуются на матрице?

2024-11-24 10:10 UTC, chekoopa commented on resources/platform/tjc-ms1-lmp-a3-1.0.json
> +          "description": "Мигает кнопкой определенное количество раз с определенной длительностью каждого мигания"
Кнопкой? Это же светодиод.

2024-11-24 10:11 UTC, chekoopa commented on resources/platform/tjc-ms1-lmp-a3-1.0.json
> +  "components": {
Добавить шину!

2024-11-24 10:13 UTC, chekoopa commented on resources/platform/tjc-ms1-mtrx-a1-1.0.json
> +          "type": "uint32_t",
Должна быть списком, или вообще должна отсутствовать. Нужно спросить, фиксирована ли частота пользовательской шины.

2024-11-24 10:15 UTC, chekoopa commented on resources/platform/tjc-ms1-main-a4-1.0.json
> +      },
Если ШИМ реализован, здесь должна появиться функция установки яркости.

2024-11-24 10:16 UTC, chekoopa commented on resources/platform/tjc-ms1-btn-a2-1.0.json
> +        "buttonMode": {
Этого параметра по идее здесь быть не должно.

2024-11-24 10:17 UTC, chekoopa commented on resources/platform/tjc-ms1-lmp-a3-1.0.json
> +          "type": "uint8_t",
Должно быть списком!

2024-11-24 10:17 UTC, chekoopa commented on resources/platform/tjc-ms1-btn-a2-1.0.json
> +        "pin": {
Должен быть списком, как и в остальных платах.

2024-11-24 10:18 UTC, chekoopa commented on resources/platform/tjc-ms1-lmp-a3-1.0.json
> +        "blink": {
Blink реализован и исправен?

2024-11-24 10:19 UTC, chekoopa requested changes
Недостаточно проработано, плюс рассогласовано по части МС-ТЮК. Комментарии оставил.

2024-11-25 08:58 UTC, CodeR-na-r1 commented on resources/platform/tjc-ms1-btn-a2-1.0.json
> +        "buttonMode": {
Исправил

2024-11-25 08:59 UTC, CodeR-na-r1 commented on resources/platform/tjc-ms1-main-a4-1.0.json
> +      },
Исправил (`on` c необязательным параметром яркости)

2024-11-25 09:03 UTC, CodeR-na-r1 commented on resources/platform/tjc-ms1-mtrx-a1-1.0.json
> +          "type": "uint32_t",
Я ее задаю при инициализации сериала на мк. Параметр сделал по аналогии с ардуино

2024-11-25 09:04 UTC, CodeR-na-r1 commented on resources/platform/tjc-ms1-lmp-a3-1.0.json
> +  "components": {
Ее нет!

2024-11-25 09:04 UTC, CodeR-na-r1 commented on resources/platform/ArduinoMicro-1.0.json
> +          "type": [0, 1],
Исправил

2024-11-25 09:04 UTC, CodeR-na-r1 commented on resources/platform/ArduinoUno-1.0.json
> +          "type": ["BUTTON_PULLUP", "BUTTON_PULLDOWN"],
Ок

2024-11-25 09:05 UTC, CodeR-na-r1 commented on resources/platform/tjc-ms1-lmp-a3-1.0.json
> +          "description": "Меняет состояние кнопки на противоположное"
Исправил

2024-11-25 09:09 UTC, CodeR-na-r1 commented on resources/platform/tjc-ms1-lmp-a3-1.0.json
> +          "type": "uint8_t",
Исправил

2024-11-25 09:11 UTC, CodeR-na-r1 commented on resources/platform/tjc-ms1-btn-a2-1.0.json
> +        "pin": {
Исправил

2024-11-25 10:31 UTC, chekoopa commented on resources/platform/tjc-ms1-main-a4-1.0.json
> +      },
Практичное решение, хотя может немного запутать пользователя.

2024-11-25 10:32 UTC, chekoopa commented on resources/platform/tjc-ms1-mtrx-a1-1.0.json
> +          "type": "uint32_t",
Там есть стандартизованный набор частот, хотя и можно от него отходиться. А значение по умолчанию есть?

2024-11-25 10:37 UTC, chekoopa approved these changes
Ставлю визу, чтобы вмержить и тестить. Основное есть, но не все вопросы решены.

Не хватает шины на лампочнице. 
И нужно понять с частотой передачи: делаем список или ставим значение по умолчанию.

2024-11-25 10:38 UTC, merged