Удаление фразы 'Пока что нет описания'
kruzhok-team/lapki-client pull request #431
Opened 2024-09-04 08:20 UTC by Roundabout1

При отсутствии схемы описания нет и его не должно быть, фраза 'Пока что нет описания' вводит в заблуждение. Лучше если на месте описания ничего не будет написано.
![image](https://github.com/user-attachments/assets/94fd6d87-7db7-473a-bf5d-e7f88deabbaa)
![image](https://github.com/user-attachments/assets/9bea6c76-1665-4050-a2dc-345c743046ce)

2024-09-05 05:39 UTC, chekoopa commented on src/renderer/src/components/CreateSchemeModal/PlatformSelection.tsx
> -      <div>{selectedPlatform?.description || 'Пока что нет описания'}</div>
Вообще, более эффектно будет более прозрачным текстом выводить приглашение типа «Для начала работы выберите платформу из списка слева. Платформа определяет, для чего создаётся схема и с помощью каких элементов.»

2024-09-05 05:40 UTC, chekoopa requested changes
Рассмотри предлагаемый вариант в комментарии.

2024-09-05 11:48 UTC, Roundabout1 commented on src/renderer/src/components/CreateSchemeModal/PlatformSelection.tsx
> -      <div>{selectedPlatform?.description || 'Пока что нет описания'}</div>
Светлая тема:
![image](https://github.com/user-attachments/assets/376c73c3-e55a-45e8-a392-0582c6a21797)
Тёмная тема:
![image](https://github.com/user-attachments/assets/43d0f8e5-62e9-4d31-864f-d2cefa3614f1)

2024-09-06 09:57 UTC, chekoopa approved these changes

2024-09-06 09:57 UTC, merged