Атрибуты как параметры
kruzhok-team/lapki-client pull request #464
Opened 2024-11-14 12:06 UTC by Roundabout1

В качестве параметров можно отправлять либо литералы, либо атрибуты других компонентов. 

**ПРОБЛЕМА**: редактор не может загрузить схему, где в качестве параметра используется атрибут. Он считает их за неизвестные компоненты.

2024-11-20 12:56 UTC, Roundabout1 commented
Возникла проблема с переименованием после слияния с мультидоком, после мержа этого PR https://github.com/kruzhok-team/lapki-client/pull/472 можно будет вмержить этот PR.

2024-11-26 06:16 UTC, chekoopa commented on src/renderer/src/lib/data/ModelController/CanvasController.ts
> +                continue;
А continue тут точно нужны? Уточни, зачем они.

2024-11-26 06:20 UTC, chekoopa reviewed
Нужна итерация.

2024-11-26 08:15 UTC, Roundabout1 commented on src/renderer/src/components/NodeModal/ActionsModal/ActionsModalParameters.tsx
> +      const delimiter = proto?.singletone && !platform.startsWith('Bearloga') ? '::' : '.';
Из платформы можно достать только разделитель для статических компонентов ('::')

2024-11-26 09:15 UTC, L140-beep commented on src/renderer/src/components/NodeModal/ActionsModal/ActionsModalParameters.tsx
> +      const delimiter = proto?.singletone && !platform.startsWith('Bearloga') ? '::' : '.';
Если объект не статический, то `.`

2024-11-26 13:29 UTC, L140-beep requested changes

2024-11-26 13:29 UTC, L140-beep commented on src/renderer/src/components/NodeModal/ActionsModal/ActionsModalParameters.tsx
> +  const Component = 'label';
Почему нельзя просто `<label>` использовать?

2024-11-26 13:29 UTC, L140-beep commented on src/renderer/src/components/NodeModal/ActionsModal/ActionsModalParameters.tsx
> +
Почему не:
```ts
    const getAll = controller.platform[smId].getAvailableVariables;
    const getImg = controller.platform[smId].getVariableIconUrl;
```

2024-11-26 13:29 UTC, L140-beep commented on src/renderer/src/components/NodeModal/ActionsModal/ActionsModalParameters.tsx
> +        const platform = getPlatform(stateMachines[smId].platform);
Мы можем получить платформу через `controller.platform[smId].data`

2024-11-26 14:30 UTC, L140-beep commented on src/renderer/src/components/NodeModal/ActionsModal/ActionsModal.tsx
> +        modelController={modelController}
```ts
const modelController = useModelContext();
```

2024-11-27 00:34 UTC, L140-beep requested changes

2024-11-27 00:34 UTC, L140-beep commented on src/renderer/src/components/NodeModal/ActionsModal/ActionsModalParameters.tsx
> +    return getAll
Почему через call сделано? Там контекст теряется?

2024-11-27 04:52 UTC, Roundabout1 commented on src/renderer/src/components/NodeModal/ActionsModal/ActionsModalParameters.tsx
> +        proto?.singletone && !platform.id.startsWith('Bearloga')
У нас тогда параметры в Берлоге будут запиываться через '::', например: `МодульДвижения.ЗадатьКоординатуВверх(Счётчик::ТекущееЗначениеСчетчика)`.
Это то как должно быть? Или тут всё таки через точку надо записывать?

2024-11-27 05:21 UTC, L140-beep commented on src/renderer/src/components/NodeModal/ActionsModal/ActionsModalParameters.tsx
> +        proto?.singletone && !platform.id.startsWith('Bearloga')
У нас просто ошибка в одной платформе Берлоги `BearlogaDefend-1.0.json`, там в качестве статического разделителя сейчас указано `::` и нужно указать `.`

2024-11-27 05:22 UTC, L140-beep commented on src/renderer/src/components/NodeModal/ActionsModal/ActionsModalParameters.tsx
> +    return getAll
Если не теряется, то можно просто 
```ts
controller.platform[smId].getAvailableVariables.map
```

2024-11-27 08:44 UTC, L140-beep approved these changes
LGTM

2024-11-27 08:47 UTC, chekoopa approved these changes

2024-11-27 08:48 UTC, merged