Загрузчик МС-ТЮК + Мультидок
kruzhok-team/lapki-client pull request #467
Opened 2024-11-15 11:05 UTC by Roundabout1

Добавлена возможность выбора машины состояний через селектор в менеджере МС-ТЮК.

Эта ветка является результатом слияния https://github.com/kruzhok-team/lapki-client/pull/456 и https://github.com/kruzhok-team/lapki-client/pull/423.

2024-11-24 10:20 UTC, chekoopa commented on src/renderer/src/types/FlasherTypes.ts
> +    this.flashMsg = flashMsg;
Строка задублирована.

2024-11-24 10:31 UTC, chekoopa approved these changes
Выглядит окей, можно вмержить и смотреть. 

Стоит поправить проблему в комментарии, плюс что найдут в других ревью.

2024-11-24 10:49 UTC, L140-beep requested changes

2024-11-24 10:49 UTC, L140-beep commented on src/main/settings.ts
> +      RefBlUserCode: string; //
Здесь должен был быть комментарий?

2024-11-24 10:49 UTC, L140-beep commented on src/main/settings.ts
>    serialmonitor: {
@chekoopa, нормально, что мы смешиваем общие настройки (тема/настройки канваса/ платформы) со специфичными (настройки МС-ТЮК, Serial Monitor)?

2024-11-24 10:49 UTC, L140-beep commented on src/renderer/src/components/AddressBook.tsx
> +              // перезапуск IDE может помочь в этом случае
@chekoopa, Мб адресную книгу хранить не глобально, а в Elements и сохранять в схеме в виде ноды с ключом "dLapkiAddressBook"? Тогда и не нужно будет IDE перезапускать

2024-11-24 10:49 UTC, L140-beep commented on src/main/settings.ts
> +      RefBlUserCode: string; //
Поменяй тип на MetaData | undefined, ты же его описал во FlasherTypes, и, я думаю, MetaType тоже следует во FlasherTypes перенести

2024-11-24 11:36 UTC, L140-beep commented on src/renderer/src/components/AddressBook.tsx
> +              // перезапуск IDE может помочь в этом случае
Или в мета-ноде

2024-11-24 11:53 UTC, chekoopa commented on src/main/settings.ts
> +      RefBlUserCode: string; //
Комментарий по идее должен быть, да.
Насчёт типа: обрати внимание, что это бэкенд. Не уверен, стоит ли импортировать что-то из отрисовки.

2024-11-24 11:55 UTC, chekoopa commented on src/renderer/src/components/AddressBook.tsx
> +              // перезапуск IDE может помочь в этом случае
Адресная книга существует на уровне клиента, а не схемы. Класть в неё конкретные адреса устройств не имеет смысла.

2024-11-24 11:58 UTC, chekoopa commented on src/main/settings.ts
>    serialmonitor: {
Вообще, нормально, в более крупных IDE это решается за счёт группировки настроек. У нас такого сейчас в полной мере нет, но хотя бы частично. По-хорошему, немного перегруппировал бы ключи, в том числе сделал для МС-ТЮКа группу tjcms, в которой уже лежали бы менеджер и адресная книга.

2024-11-24 12:08 UTC, L140-beep commented on src/main/settings.ts
> +      RefBlUserCode: string; //
А, ну тогда, да

2024-11-25 05:33 UTC, Roundabout1 commented on src/main/settings.ts
> +      RefBlUserCode: string; //
Комментарии взяты из [ms1-go](https://github.com/polyus-nt/ms1-go/blob/c13aa2a014495d40a6abdd7beb0834d98689f368/pkg/ms1/Reply.go#L128). Там также отсутствует комментарий и я не знаю, что должен означать RefBlUserCode

2024-11-25 05:37 UTC, merged