Редизайн клиента.
kruzhok-team/lapki-client pull request #48
Opened 2023-10-09 09:03 UTC by XidFanSan

1) Исправлены грамматические и незначительные ошибки в клиенте;
2) Редизайн модального окна;
3) Редизайн начального экрана клиента;
4) При добавлении события через контекстное меню добавляется состояние.

2023-10-09 10:07 UTC, chekoopa requested changes

2023-10-09 10:07 UTC, chekoopa commented on src/renderer/src/assets/icons/maximize.svg
То же, что и для `arrow_down_right.svg`, тем более что у него и `minimize` цвета отличаются.

2023-10-09 10:07 UTC, chekoopa commented on src/renderer/src/assets/icons/maximize.svg
Надеюсь, ты все значки брал под подходящей лицензией? Вижу, что у сайта `icon666.com` висит неограниченная лицензия без атрибуции, это допустимо.

2023-10-09 10:07 UTC, chekoopa commented on src/renderer/src/components/DiagramContextMenu.tsx
> +    children?: string[];
У тебя же уже есть `DiagramContextMenuItem`...

2023-10-09 10:07 UTC, chekoopa commented on src/renderer/src/components/DiagramContextMenu.tsx
> +      combination: 'Ctrl+C',
В будущем надо будет выносить горячие клавиши в отдельную единую точку, по многим причинам.

2023-10-09 10:07 UTC, chekoopa commented on src/renderer/src/hooks/useDiagramContextMenu.ts
> +  children?: string[];
`children` тоже может быть `DiagramContextMenuItem`.

2023-10-10 02:56 UTC, XidFanSan commented on src/renderer/src/assets/icons/icon.svg
.svg используется здесь, чтобы качество не урезалось, а вот для самой IDE .img используется, вот и пришлось пойти на крайние меры.

2023-10-10 02:56 UTC, XidFanSan commented on src/renderer/src/assets/icons/arrow_down_right.svg
Хорошо, сделаю.

2023-10-10 02:57 UTC, XidFanSan commented on src/renderer/src/assets/icons/maximize.svg
Это исправлю, я их взял заранее, чтобы позже решили куда их добавлять.

2023-10-10 02:58 UTC, XidFanSan commented on src/renderer/src/assets/icons/maximize.svg
Да, все с подходящей лицензией, я стараюсь на это обращать внимание, потому что лишнее указание авторства нам ни к чему.

2023-10-10 03:00 UTC, XidFanSan commented on src/renderer/src/components/DiagramContextMenu.tsx
> +    children?: string[];
Данная передача переменных была уже реализована Никитой, поэтому я решил не портить сделанную логику и просто добавил что было мне необходимо.

2023-10-10 03:02 UTC, XidFanSan commented on src/renderer/src/components/DiagramContextMenu.tsx
> +      combination: 'Ctrl+C',
Понимаю, думал об этом, потому что даже прописывание событий происходит в разных файлах, хоть это и мало где встречается, но оно есть.

2023-10-10 03:03 UTC, XidFanSan commented on src/renderer/src/lib/basic/Keyboard.ts
> +        this.emit('ctrla', e);
А, ой, я писал до этого ctrlshifta, видимо изменения не сохранил

2023-10-11 15:25 UTC, bryzZz requested changes

2023-10-11 15:37 UTC, merged

2023-10-11 15:38 UTC, chekoopa commented
Решено вмержить текущую версию и добавить доработки (рефакторинг и доработка подменю) следующим реквестом.