Сохранение и загрузка адреса удалённого сервера через electron-settings + улучшение интерфейса
kruzhok-team/lapki-client pull request #77
Opened 2023-10-30 16:14 UTC by Roundabout1

1. Реализованы сохранение и загрузка порта и хоста через electron-settings, а не через localStorage, как это было раньше.
2. Немного улучшено мсдальное окно выбора загрузчика: по-умолчанию открывается окно выбора удалённого загрузчика, также состояние окна не сбрасывается при закрытии, то есть если пользователь открыл окно локального загрузчика, закрыл меню, то в следующий раз откроется это же окно.
3. Вместо использования литералов, ключи и параметры electron-settings передаются из main в renderer через window.api.

2023-10-30 16:54 UTC, chekoopa requested changes
Есть логичные правки, но перетаскивать локальный порт в эти же настройки – затея гиблая. Да, их надо доставать с бэкенда, но не из настроек, которые пишутся в файл.

2023-10-30 16:54 UTC, chekoopa commented on src/main/electron-settings-consts.ts
> +    localPort: string;
Суть локального хоста именно в том, что адрес `localhost` и порт назначаются самим бэкендом. Нельзя это класть в настройки. Тут нужны лишь `remoteHost` и `remotePort`, ну и флаг при желании, типа `remoteOnLaunch`.

2023-10-30 16:54 UTC, chekoopa commented on src/main/index.ts
> +      port: DEFAULT_COMPILER_PORT,
Рациональнее выносить объект в константу целиком.

2023-10-30 16:54 UTC, chekoopa commented on src/main/index.ts
> -
Дублирую: история с локальным портом состояла именно в динамичности, зря ты это убрал.

2023-10-31 06:39 UTC, Roundabout1 commented on src/main/index.ts
> +      port: DEFAULT_COMPILER_PORT,
Вынес в отдельную константу

2023-10-31 06:39 UTC, Roundabout1 commented on src/main/index.ts
> -
Вернул старый способ получения локального хоста и порта

2023-11-11 04:29 UTC, bryzZz approved these changes

2023-11-11 10:39 UTC, chekoopa approved these changes

2023-11-11 10:39 UTC, merged