Вывести адрес компилятора и доксервера в настройки (electron-settings)
kruzhok-team/lapki-client pull request #95
Opened 2023-11-17 10:53 UTC by Roundabout1

![image](https://github.com/kruzhok-team/lapki-client/assets/86153878/f1efe71d-d86d-476e-a40b-384c4e82d23a)
![image](https://github.com/kruzhok-team/lapki-client/assets/86153878/a2a10ec3-07df-4520-897e-ab4821337445)
![image](https://github.com/kruzhok-team/lapki-client/assets/86153878/6e08e355-f8dc-4e19-9e23-6e5fd3b34063)

- Добавлены кнопки для смены серверов у компилятора и документации.
- Новые модалки содержат кнопку "сбросить настройки", которые возвращают значения текстовых полей на те, что были заданы IDE в самом начале, то есть для компиялтора - это "lapki.polyus-nt.ru:8081", а для документации это "https://lapki-doc.polyus-nt.ru/".
- При подключение к новому серверу, настройки сохраняются, и при следующем запуске IDE будет пытаться подключиться к нему.
- Реализованы хранение и изменение настроек для док-сервера через electron-settings, а также передача их значений по-умолчанию через window.api.

2023-11-20 04:35 UTC, chekoopa requested changes

2023-11-20 04:35 UTC, chekoopa commented on src/renderer/src/components/Documentation/Documentation.tsx
> +import { useState, useEffect } from 'react';
Очень и очень странный дифф, сложно отследить изменения.

2023-11-20 04:35 UTC, chekoopa commented on src/renderer/src/components/Documentation/Documentation.tsx
> +var SET_URL;
Надо переделать под хук.

2023-11-20 04:35 UTC, chekoopa commented on src/renderer/src/components/Documentation/Documentation.tsx
> +        .then((data) => data.text())
Мимо прошло изначально, fetch в главном потоке – это страшно, тоже имеет смысл переделать.

2023-11-20 04:35 UTC, chekoopa commented on src/renderer/src/components/Modules/Compiler.ts
> +  static LOCAL_STORAGE_HOST = 'compiler host';
LocalStorage? Зачем он здесь? 🤔

2023-11-20 04:36 UTC, chekoopa commented
Плюс нужно поправить стили, хоть это можно и следующей итерацией.

2023-11-20 05:18 UTC, bryzZz commented on src/renderer/src/components/Modal/TextSelectOptions.tsx
> +export const TextSelectOptions = forwardRef<HTMLSelectElement, TextSelectProps>(
Этот компонент нигде не используется, зачем он?

2023-11-20 05:18 UTC, bryzZz commented on src/renderer/src/components/Sidebar/Setting.tsx
> +  const [isDocModalOpen, setIsDocModalOpen] = useState(false);
Переделай на хук useModal

2023-11-20 05:18 UTC, bryzZz commented on src/renderer/src/components/serverSelect/DocSelectModal.tsx
> +  const [hostInput, setInputHost] = useState('');
Нужно использовать либо хук useForm, и убирать состояния для инпутов(Делать интерфейс со всеми параметрами формы, передавать его в хук, инпуты регистрировать в форму с помощью функции register которую возвращает useForm, а все данные получать уже в функции handleSubmit). В таком варианте легче предусмотреть валидацию. Либо использовать только состояния для всех инпутов и в методе handleSubmit и события отключать стандартное поведение event.preventDefault(). Сейчас получается что хук useForm используется только для того чтобы он внутри сам вызвал event.preventDefault()

2023-11-20 05:18 UTC, bryzZz commented on src/renderer/src/components/serverSelect/ServerSelectModal.tsx
> +  const handleSubmit = hookHandleSubmit(() => {
Тоже самое с формой

2023-11-20 05:36 UTC, bryzZz commented on src/renderer/src/components/Documentation/Documentation.tsx
> +var SET_URL;
Неет, я только сейчас разобрался что тут. Проблема в том что electron-settings позволяет только получать и выставлять настройки а вот подписаться на их изменения нет. А ты хочешь синхронизировать настройки в двух компонентах. Мне тут пока не понятно как сделать нормально

2023-11-20 07:27 UTC, Roundabout1 commented on src/main/consts.ts
> +export const PLATFORMS_PATH_SETTINGS: string = 'PlatformsPath';
Файл теперь удалён. Он остался от старых наработок.

2023-11-20 07:29 UTC, Roundabout1 commented on src/renderer/src/components/Documentation/Documentation.tsx
> +var SET_URL;
Да, мне не удалось придумать как это сделать по другому.

2023-11-20 07:29 UTC, Roundabout1 commented on src/renderer/src/components/Modules/Compiler.ts
> +  static LOCAL_STORAGE_HOST = 'compiler host';
Удалено.

2023-11-20 07:31 UTC, Roundabout1 commented on src/renderer/src/components/Modal/TextSelectOptions.tsx
> +export const TextSelectOptions = forwardRef<HTMLSelectElement, TextSelectProps>(
Исправлено. Теперь этот компонент используется вместо TextSelectFlasher, последний компонент удалён. Этот компонент более универсальный чем старый вариант, в него можно передавать опции через параметры.

2023-11-20 07:42 UTC, Roundabout1 commented on src/renderer/src/components/Documentation/Documentation.tsx
> +import { useState, useEffect } from 'react';
Я не знаю почему гит посчитал, что весь файл был заменён, может быть это как-то связано с тем, что переход на новую строку в Windows и Linux считается по-разному и поэтому он посчитал, что все строки являются новыми, но тогда не понятно почему с другими файлами все в порядке.

2023-11-20 07:55 UTC, Roundabout1 commented on src/renderer/src/components/Sidebar/Setting.tsx
> +  const [isDocModalOpen, setIsDocModalOpen] = useState(false);
Сделано.

2023-11-23 08:25 UTC, Roundabout1 commented on src/renderer/src/components/serverSelect/DocSelectModal.tsx
> +  const [hostInput, setInputHost] = useState('');
useState заменён на useForm

2023-11-24 11:48 UTC, chekoopa commented on src/renderer/src/components/serverSelect/ServerSelectModal.tsx
> +      <button type="button" className="btn-secondary" onClick={handleReturnOriginalValues}>
Следующим PR переместить кнопку ниже, инструмент для этого есть (как кнопка удаления в редакторе компонента)

2023-11-24 11:48 UTC, chekoopa approved these changes

2023-11-24 11:48 UTC, merged